/* gender-details-interface.c generated by valac 0.26.2.1-1f25, the Vala compiler
 * generated from gender-details-interface.vala, do not modify */

/*
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Raul Gutierrez Segales <raul.gutierrez.segales@collabora.co.uk>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <tracker-test.h>
#include <folks/folks.h>
#include <stdlib.h>
#include <string.h>
#include <folks-test.h>
#include <gee.h>
#include <folks/folks-tracker.h>
#include <gio/gio.h>


#define TYPE_GENDER_DETAILS_INTERFACE_TESTS (gender_details_interface_tests_get_type ())
#define GENDER_DETAILS_INTERFACE_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GENDER_DETAILS_INTERFACE_TESTS, GenderDetailsInterfaceTests))
#define GENDER_DETAILS_INTERFACE_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GENDER_DETAILS_INTERFACE_TESTS, GenderDetailsInterfaceTestsClass))
#define IS_GENDER_DETAILS_INTERFACE_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GENDER_DETAILS_INTERFACE_TESTS))
#define IS_GENDER_DETAILS_INTERFACE_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GENDER_DETAILS_INTERFACE_TESTS))
#define GENDER_DETAILS_INTERFACE_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GENDER_DETAILS_INTERFACE_TESTS, GenderDetailsInterfaceTestsClass))

typedef struct _GenderDetailsInterfaceTests GenderDetailsInterfaceTests;
typedef struct _GenderDetailsInterfaceTestsClass GenderDetailsInterfaceTestsClass;
typedef struct _GenderDetailsInterfaceTestsPrivate GenderDetailsInterfaceTestsPrivate;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GenderDetailsInterfaceTests {
	TrackerTestTestCase parent_instance;
	GenderDetailsInterfaceTestsPrivate * priv;
};

struct _GenderDetailsInterfaceTestsClass {
	TrackerTestTestCaseClass parent_class;
};

struct _GenderDetailsInterfaceTestsPrivate {
	GMainLoop* _main_loop;
	FolksIndividualAggregator* _aggregator;
	gboolean _found_gender;
	gchar* _gender;
	gchar* _fullname;
};

struct _GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	GenderDetailsInterfaceTests* self;
	FolksBackendStore* store;
	FolksBackendStore* _tmp0_;
	FolksIndividualAggregator* _tmp1_;
	FolksIndividualAggregator* _tmp2_;
	FolksIndividualAggregator* _tmp3_;
	GError* e;
	GError* _tmp4_;
	const gchar* _tmp5_;
	GError * _inner_error_;
};


static gpointer gender_details_interface_tests_parent_class = NULL;

GType gender_details_interface_tests_get_type (void) G_GNUC_CONST;
#define GENDER_DETAILS_INTERFACE_TESTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_GENDER_DETAILS_INTERFACE_TESTS, GenderDetailsInterfaceTestsPrivate))
enum  {
	GENDER_DETAILS_INTERFACE_TESTS_DUMMY_PROPERTY
};
GenderDetailsInterfaceTests* gender_details_interface_tests_new (void);
GenderDetailsInterfaceTests* gender_details_interface_tests_construct (GType object_type);
void gender_details_interface_tests_test_gender_details_interface (GenderDetailsInterfaceTests* self);
static void _gender_details_interface_tests_test_gender_details_interface_folks_test_case_test_method (gpointer self);
static void _gender_details_interface_tests_test_gender_details_interface_async (GenderDetailsInterfaceTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void _gender_details_interface_tests_test_gender_details_interface_finish (GenderDetailsInterfaceTests* self, GAsyncResult* _res_);
static void _gender_details_interface_tests_test_gender_details_interface_async_data_free (gpointer _data);
static gboolean _gender_details_interface_tests_test_gender_details_interface_async_co (GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_);
static void _gender_details_interface_tests_test_gender_details_interface_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _gender_details_interface_tests_individuals_changed_cb (GenderDetailsInterfaceTests* self, GeeMultiMap* changes);
static void __gender_details_interface_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self);
static void _gender_details_interface_tests_notify_gender_cb (GenderDetailsInterfaceTests* self, GObject* individual_obj, GParamSpec* ps);
static void __gender_details_interface_tests_notify_gender_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void gender_details_interface_tests_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


static void _gender_details_interface_tests_test_gender_details_interface_folks_test_case_test_method (gpointer self) {
#line 38 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	gender_details_interface_tests_test_gender_details_interface ((GenderDetailsInterfaceTests*) self);
#line 116 "gender-details-interface.c"
}


GenderDetailsInterfaceTests* gender_details_interface_tests_construct (GType object_type) {
	GenderDetailsInterfaceTests * self = NULL;
#line 36 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self = (GenderDetailsInterfaceTests*) tracker_test_test_case_construct (object_type, "GenderDetailsInterfaceTests");
#line 38 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_test_case_add_test ((FolksTestCase*) self, "test gender details interface", _gender_details_interface_tests_test_gender_details_interface_folks_test_case_test_method, g_object_ref (self), g_object_unref);
#line 34 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return self;
#line 128 "gender-details-interface.c"
}


GenderDetailsInterfaceTests* gender_details_interface_tests_new (void) {
#line 34 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return gender_details_interface_tests_construct (TYPE_GENDER_DETAILS_INTERFACE_TESTS);
#line 135 "gender-details-interface.c"
}


void gender_details_interface_tests_test_gender_details_interface (GenderDetailsInterfaceTests* self) {
	GMainLoop* _tmp0_ = NULL;
	GeeHashMap* c1 = NULL;
	GeeHashMap* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	TrackerTestBackend* _tmp6_ = NULL;
	TrackerTestBackend* _tmp7_ = NULL;
	GMainLoop* _tmp8_ = NULL;
	gboolean _tmp9_ = FALSE;
#line 42 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (self != NULL);
#line 44 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp0_ = g_main_loop_new (NULL, FALSE);
#line 44 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 44 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self->priv->_main_loop = _tmp0_;
#line 45 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 45 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	c1 = _tmp1_;
#line 46 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp2_ = g_strdup ("persona #1");
#line 46 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_free0 (self->priv->_fullname);
#line 46 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self->priv->_fullname = _tmp2_;
#line 47 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp3_ = g_strdup (TRF_ONTOLOGY_DEFS_NCO_MALE);
#line 47 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_free0 (self->priv->_gender);
#line 47 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self->priv->_gender = _tmp3_;
#line 49 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp4_ = self->priv->_fullname;
#line 49 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	gee_abstract_map_set ((GeeAbstractMap*) c1, TRF_ONTOLOGY_DEFS_NCO_FULLNAME, _tmp4_);
#line 50 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp5_ = self->priv->_gender;
#line 50 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	gee_abstract_map_set ((GeeAbstractMap*) c1, TRF_ONTOLOGY_DEFS_NCO_GENDER, _tmp5_);
#line 51 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp6_ = ((TrackerTestTestCase*) self)->tracker_backend;
#line 51 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	tracker_test_backend_add_contact (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, TRACKER_TEST_TYPE_BACKEND, TrackerTestBackend), c1);
#line 52 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp7_ = ((TrackerTestTestCase*) self)->tracker_backend;
#line 52 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	tracker_test_backend_set_up (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, TRACKER_TEST_TYPE_BACKEND, TrackerTestBackend));
#line 54 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self->priv->_found_gender = FALSE;
#line 56 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_gender_details_interface_tests_test_gender_details_interface_async (self, NULL, NULL);
#line 58 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp8_ = self->priv->_main_loop;
#line 58 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_test_utils_loop_run_with_timeout (_tmp8_, 5);
#line 60 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp9_ = self->priv->_found_gender;
#line 60 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_vala_assert (_tmp9_ == TRUE, "this._found_gender == true");
#line 42 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (c1);
#line 205 "gender-details-interface.c"
}


static void _gender_details_interface_tests_test_gender_details_interface_async_data_free (gpointer _data) {
	GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_;
	_data_ = _data;
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (_data_->self);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_slice_free (GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData, _data_);
#line 216 "gender-details-interface.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return self ? g_object_ref (self) : NULL;
#line 223 "gender-details-interface.c"
}


static void _gender_details_interface_tests_test_gender_details_interface_async (GenderDetailsInterfaceTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_;
	GenderDetailsInterfaceTests* _tmp0_ = NULL;
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_ = g_slice_new0 (GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, _gender_details_interface_tests_test_gender_details_interface_async);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, _gender_details_interface_tests_test_gender_details_interface_async_data_free);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->self = _tmp0_;
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_gender_details_interface_tests_test_gender_details_interface_async_co (_data_);
#line 242 "gender-details-interface.c"
}


static void _gender_details_interface_tests_test_gender_details_interface_finish (GenderDetailsInterfaceTests* self, GAsyncResult* _res_) {
	GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_;
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 250 "gender-details-interface.c"
}


static void _gender_details_interface_tests_test_gender_details_interface_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_ = _user_data_;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_source_object_ = source_object;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_res_ = _res_;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_gender_details_interface_tests_test_gender_details_interface_async_co (_data_);
#line 264 "gender-details-interface.c"
}


static void __gender_details_interface_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self) {
#line 68 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_gender_details_interface_tests_individuals_changed_cb ((GenderDetailsInterfaceTests*) self, changes);
#line 271 "gender-details-interface.c"
}


static gboolean _gender_details_interface_tests_test_gender_details_interface_async_co (GenderDetailsInterfaceTestsTestGenderDetailsInterfaceAsyncData* _data_) {
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	switch (_data_->_state_) {
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		case 0:
#line 280 "gender-details-interface.c"
		goto _state_0;
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		case 1:
#line 284 "gender-details-interface.c"
		goto _state_1;
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		case 2:
#line 288 "gender-details-interface.c"
		goto _state_2;
		default:
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_assert_not_reached ();
#line 293 "gender-details-interface.c"
	}
	_state_0:
#line 65 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp0_ = NULL;
#line 65 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp0_ = folks_backend_store_dup ();
#line 65 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->store = _data_->_tmp0_;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_state_ = 1;
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_backend_store_prepare (_data_->store, _gender_details_interface_tests_test_gender_details_interface_async_ready, _data_);
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return FALSE;
#line 308 "gender-details-interface.c"
	_state_1:
#line 66 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_backend_store_prepare_finish (_data_->store, _data_->_res_);
#line 67 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp1_ = NULL;
#line 67 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp1_ = folks_individual_aggregator_dup ();
#line 67 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (_data_->self->priv->_aggregator);
#line 67 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->self->priv->_aggregator = _data_->_tmp1_;
#line 68 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp2_ = NULL;
#line 68 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_data_->_tmp2_ = _data_->self->priv->_aggregator;
#line 68 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_signal_connect_object (_data_->_tmp2_, "individuals-changed-detailed", (GCallback) __gender_details_interface_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed, _data_->self, 0);
#line 326 "gender-details-interface.c"
	{
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp3_ = NULL;
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp3_ = _data_->self->priv->_aggregator;
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_state_ = 2;
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		folks_individual_aggregator_prepare (_data_->_tmp3_, _gender_details_interface_tests_test_gender_details_interface_async_ready, _data_);
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		return FALSE;
#line 338 "gender-details-interface.c"
		_state_2:
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		folks_individual_aggregator_prepare_finish (_data_->_tmp3_, _data_->_res_, &_data_->_inner_error_);
#line 72 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 344 "gender-details-interface.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->e = _data_->_inner_error_;
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_inner_error_ = NULL;
#line 76 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp4_ = NULL;
#line 76 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp4_ = _data_->e;
#line 76 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp5_ = NULL;
#line 76 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_data_->_tmp5_ = _data_->_tmp4_->message;
#line 76 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_warning ("gender-details-interface.vala:76: Error when calling prepare: %s\n", _data_->_tmp5_);
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_g_error_free0 (_data_->e);
#line 367 "gender-details-interface.c"
	}
	__finally0:
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	if (G_UNLIKELY (_data_->_inner_error_ != NULL)) {
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_g_object_unref0 (_data_->store);
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_clear_error (&_data_->_inner_error_);
#line 70 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		return FALSE;
#line 380 "gender-details-interface.c"
	}
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (_data_->store);
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	if (_data_->_state_ == 0) {
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 388 "gender-details-interface.c"
	} else {
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 392 "gender-details-interface.c"
	}
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_object_unref (_data_->_async_result);
#line 63 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return FALSE;
#line 398 "gender-details-interface.c"
}


static void __gender_details_interface_tests_notify_gender_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 92 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_gender_details_interface_tests_notify_gender_cb ((GenderDetailsInterfaceTests*) self, _sender, pspec);
#line 405 "gender-details-interface.c"
}


static void _gender_details_interface_tests_individuals_changed_cb (GenderDetailsInterfaceTests* self, GeeMultiMap* changes) {
	GeeCollection* added = NULL;
	GeeMultiMap* _tmp0_ = NULL;
	GeeCollection* _tmp1_ = NULL;
	GeeSet* removed = NULL;
	GeeMultiMap* _tmp2_ = NULL;
	GeeSet* _tmp3_ = NULL;
	GeeSet* _tmp20_ = NULL;
	gint _tmp21_ = 0;
	gint _tmp22_ = 0;
#line 80 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (self != NULL);
#line 80 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (changes != NULL);
#line 83 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp0_ = changes;
#line 83 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp1_ = gee_multi_map_get_values (_tmp0_);
#line 83 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	added = _tmp1_;
#line 84 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp2_ = changes;
#line 84 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp3_ = gee_multi_map_get_keys (_tmp2_);
#line 84 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	removed = _tmp3_;
#line 435 "gender-details-interface.c"
	{
		GeeIterator* _i_it = NULL;
		GeeCollection* _tmp4_ = NULL;
		GeeIterator* _tmp5_ = NULL;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_tmp4_ = added;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_i_it = _tmp5_;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		while (TRUE) {
#line 448 "gender-details-interface.c"
			GeeIterator* _tmp6_ = NULL;
			gboolean _tmp7_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp8_ = NULL;
			gpointer _tmp9_ = NULL;
			FolksIndividual* _tmp10_ = NULL;
			FolksIndividual* _tmp11_ = NULL;
			const gchar* _tmp12_ = NULL;
			const gchar* _tmp13_ = NULL;
			const gchar* _tmp14_ = NULL;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp6_ = _i_it;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			if (!_tmp7_) {
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				break;
#line 467 "gender-details-interface.c"
			}
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp8_ = _i_it;
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			i = (FolksIndividual*) _tmp9_;
#line 88 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp10_ = i;
#line 88 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_vala_assert (_tmp10_ != NULL, "i != null");
#line 90 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp11_ = i;
#line 90 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp12_ = folks_name_details_get_full_name ((FolksNameDetails*) _tmp11_);
#line 90 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp13_ = _tmp12_;
#line 90 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp14_ = self->priv->_fullname;
#line 90 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
#line 489 "gender-details-interface.c"
				FolksIndividual* _tmp15_ = NULL;
				FolksIndividual* _tmp16_ = NULL;
				FolksGender _tmp17_ = 0;
				FolksGender _tmp18_ = 0;
#line 92 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				_tmp15_ = i;
#line 92 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				g_signal_connect_object ((GObject*) _tmp15_, "notify::gender", (GCallback) __gender_details_interface_tests_notify_gender_cb_g_object_notify, self, 0);
#line 93 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				_tmp16_ = i;
#line 93 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				_tmp17_ = folks_gender_details_get_gender ((FolksGenderDetails*) _tmp16_);
#line 93 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				_tmp18_ = _tmp17_;
#line 93 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				if (_tmp18_ == FOLKS_GENDER_MALE) {
#line 506 "gender-details-interface.c"
					GMainLoop* _tmp19_ = NULL;
#line 95 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
					self->priv->_found_gender = TRUE;
#line 96 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
					_tmp19_ = self->priv->_main_loop;
#line 96 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
					g_main_loop_quit (_tmp19_);
#line 514 "gender-details-interface.c"
				}
			}
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_g_object_unref0 (i);
#line 519 "gender-details-interface.c"
		}
#line 86 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_g_object_unref0 (_i_it);
#line 523 "gender-details-interface.c"
	}
#line 101 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp20_ = removed;
#line 101 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp21_ = gee_collection_get_size ((GeeCollection*) _tmp20_);
#line 101 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp22_ = _tmp21_;
#line 101 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_vala_assert (_tmp22_ == 1, "removed.size == 1");
#line 533 "gender-details-interface.c"
	{
		GeeIterator* _i_it = NULL;
		GeeSet* _tmp23_ = NULL;
		GeeIterator* _tmp24_ = NULL;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_tmp23_ = removed;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_tmp24_ = gee_iterable_iterator ((GeeIterable*) _tmp23_);
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_i_it = _tmp24_;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		while (TRUE) {
#line 546 "gender-details-interface.c"
			GeeIterator* _tmp25_ = NULL;
			gboolean _tmp26_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp27_ = NULL;
			gpointer _tmp28_ = NULL;
			FolksIndividual* _tmp29_ = NULL;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp25_ = _i_it;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp26_ = gee_iterator_next (_tmp25_);
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			if (!_tmp26_) {
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
				break;
#line 561 "gender-details-interface.c"
			}
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp27_ = _i_it;
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp28_ = gee_iterator_get (_tmp27_);
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			i = (FolksIndividual*) _tmp28_;
#line 105 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_tmp29_ = i;
#line 105 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_vala_assert (_tmp29_ == NULL, "i == null");
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
			_g_object_unref0 (i);
#line 575 "gender-details-interface.c"
		}
#line 103 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_g_object_unref0 (_i_it);
#line 579 "gender-details-interface.c"
	}
#line 80 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (removed);
#line 80 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (added);
#line 585 "gender-details-interface.c"
}


static void _gender_details_interface_tests_notify_gender_cb (GenderDetailsInterfaceTests* self, GObject* individual_obj, GParamSpec* ps) {
	FolksIndividual* individual = NULL;
	GObject* _tmp0_ = NULL;
	FolksIndividual* _tmp1_ = NULL;
	FolksIndividual* _tmp2_ = NULL;
	FolksGender _tmp3_ = 0;
	FolksGender _tmp4_ = 0;
#line 109 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (self != NULL);
#line 109 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (individual_obj != NULL);
#line 109 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_return_if_fail (ps != NULL);
#line 111 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp0_ = individual_obj;
#line 111 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, FOLKS_TYPE_INDIVIDUAL, FolksIndividual));
#line 111 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	individual = _tmp1_;
#line 112 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp2_ = individual;
#line 112 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp3_ = folks_gender_details_get_gender ((FolksGenderDetails*) _tmp2_);
#line 112 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp4_ = _tmp3_;
#line 112 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	if (_tmp4_ == FOLKS_GENDER_MALE) {
#line 616 "gender-details-interface.c"
		GMainLoop* _tmp5_ = NULL;
#line 114 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		self->priv->_found_gender = TRUE;
#line 115 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		_tmp5_ = self->priv->_main_loop;
#line 115 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
		g_main_loop_quit (_tmp5_);
#line 624 "gender-details-interface.c"
	}
#line 109 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (individual);
#line 628 "gender-details-interface.c"
}


static void gender_details_interface_tests_class_init (GenderDetailsInterfaceTestsClass * klass) {
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	gender_details_interface_tests_parent_class = g_type_class_peek_parent (klass);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_type_class_add_private (klass, sizeof (GenderDetailsInterfaceTestsPrivate));
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	G_OBJECT_CLASS (klass)->finalize = gender_details_interface_tests_finalize;
#line 639 "gender-details-interface.c"
}


static void gender_details_interface_tests_instance_init (GenderDetailsInterfaceTests * self) {
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self->priv = GENDER_DETAILS_INTERFACE_TESTS_GET_PRIVATE (self);
#line 646 "gender-details-interface.c"
}


static void gender_details_interface_tests_finalize (GObject* obj) {
	GenderDetailsInterfaceTests * self;
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_GENDER_DETAILS_INTERFACE_TESTS, GenderDetailsInterfaceTests);
#line 28 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 29 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (self->priv->_aggregator);
#line 31 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_free0 (self->priv->_gender);
#line 32 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_free0 (self->priv->_fullname);
#line 26 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	G_OBJECT_CLASS (gender_details_interface_tests_parent_class)->finalize (obj);
#line 664 "gender-details-interface.c"
}


GType gender_details_interface_tests_get_type (void) {
	static volatile gsize gender_details_interface_tests_type_id__volatile = 0;
	if (g_once_init_enter (&gender_details_interface_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GenderDetailsInterfaceTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gender_details_interface_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GenderDetailsInterfaceTests), 0, (GInstanceInitFunc) gender_details_interface_tests_instance_init, NULL };
		GType gender_details_interface_tests_type_id;
		gender_details_interface_tests_type_id = g_type_register_static (TRACKER_TEST_TYPE_TEST_CASE, "GenderDetailsInterfaceTests", &g_define_type_info, 0);
		g_once_init_leave (&gender_details_interface_tests_type_id__volatile, gender_details_interface_tests_type_id);
	}
	return gender_details_interface_tests_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	GenderDetailsInterfaceTests* tests = NULL;
	GenderDetailsInterfaceTests* _tmp0_ = NULL;
#line 122 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_test_init (&args_length1, &args, NULL);
#line 124 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_tmp0_ = gender_details_interface_tests_new ();
#line 124 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	tests = _tmp0_;
#line 125 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_test_case_register ((FolksTestCase*) tests);
#line 126 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	g_test_run ();
#line 127 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	folks_test_case_final_tear_down ((FolksTestCase*) tests);
#line 129 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	result = 0;
#line 129 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	_g_object_unref0 (tests);
#line 129 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return result;
#line 702 "gender-details-interface.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 120 "/opt/gnome3/source/folks/tests/tracker/gender-details-interface.vala"
	return _vala_main (argv, argc);
#line 712 "gender-details-interface.c"
}



