/* individual-retrieval.c generated by valac 0.20.1.30-1b1d, the Vala compiler
 * generated from individual-retrieval.vala, do not modify */

/*
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Raul Gutierrez Segales <raul.gutierrez.segales@collabora.co.uk>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <tracker-test.h>
#include <folks/folks.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <folks-test.h>
#include <folks/folks-tracker.h>
#include <gio/gio.h>


#define TYPE_INDIVIDUAL_RETRIEVAL_TESTS (individual_retrieval_tests_get_type ())
#define INDIVIDUAL_RETRIEVAL_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_INDIVIDUAL_RETRIEVAL_TESTS, IndividualRetrievalTests))
#define INDIVIDUAL_RETRIEVAL_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_INDIVIDUAL_RETRIEVAL_TESTS, IndividualRetrievalTestsClass))
#define IS_INDIVIDUAL_RETRIEVAL_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_INDIVIDUAL_RETRIEVAL_TESTS))
#define IS_INDIVIDUAL_RETRIEVAL_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_INDIVIDUAL_RETRIEVAL_TESTS))
#define INDIVIDUAL_RETRIEVAL_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_INDIVIDUAL_RETRIEVAL_TESTS, IndividualRetrievalTestsClass))

typedef struct _IndividualRetrievalTests IndividualRetrievalTests;
typedef struct _IndividualRetrievalTestsClass IndividualRetrievalTestsClass;
typedef struct _IndividualRetrievalTestsPrivate IndividualRetrievalTestsPrivate;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _IndividualRetrievalTestsTestSingletonIndividualsAsyncData IndividualRetrievalTestsTestSingletonIndividualsAsyncData;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _IndividualRetrievalTests {
	TrackerTestTestCase parent_instance;
	IndividualRetrievalTestsPrivate * priv;
};

struct _IndividualRetrievalTestsClass {
	TrackerTestTestCaseClass parent_class;
};

struct _IndividualRetrievalTestsPrivate {
	GMainLoop* _main_loop;
	FolksIndividualAggregator* _aggregator;
	GeeHashMap* _c1;
	GeeHashMap* _c2;
};

struct _IndividualRetrievalTestsTestSingletonIndividualsAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	IndividualRetrievalTests* self;
	FolksBackendStore* store;
	FolksBackendStore* _tmp0_;
	FolksIndividualAggregator* _tmp1_;
	FolksIndividualAggregator* _tmp2_;
	FolksIndividualAggregator* _tmp3_;
	GError* e;
	GError* _tmp4_;
	const gchar* _tmp5_;
	GError * _inner_error_;
};


static gpointer individual_retrieval_tests_parent_class = NULL;

GType individual_retrieval_tests_get_type (void) G_GNUC_CONST;
#define INDIVIDUAL_RETRIEVAL_TESTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_INDIVIDUAL_RETRIEVAL_TESTS, IndividualRetrievalTestsPrivate))
enum  {
	INDIVIDUAL_RETRIEVAL_TESTS_DUMMY_PROPERTY
};
IndividualRetrievalTests* individual_retrieval_tests_new (void);
IndividualRetrievalTests* individual_retrieval_tests_construct (GType object_type);
void individual_retrieval_tests_test_singleton_individuals (IndividualRetrievalTests* self);
static void _individual_retrieval_tests_test_singleton_individuals_folks_test_case_test_method (gpointer self);
static void _individual_retrieval_tests_test_singleton_individuals_async (IndividualRetrievalTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void _individual_retrieval_tests_test_singleton_individuals_finish (IndividualRetrievalTests* self, GAsyncResult* _res_);
static void _individual_retrieval_tests_test_singleton_individuals_async_data_free (gpointer _data);
static gboolean _individual_retrieval_tests_test_singleton_individuals_async_co (IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_);
static void _individual_retrieval_tests_test_singleton_individuals_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _individual_retrieval_tests_individuals_changed_cb (IndividualRetrievalTests* self, GeeMultiMap* changes);
static void __individual_retrieval_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self);
static void individual_retrieval_tests_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


static void _individual_retrieval_tests_test_singleton_individuals_folks_test_case_test_method (gpointer self) {
#line 37 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	individual_retrieval_tests_test_singleton_individuals (self);
#line 113 "individual-retrieval.c"
}


IndividualRetrievalTests* individual_retrieval_tests_construct (GType object_type) {
	IndividualRetrievalTests * self = NULL;
#line 35 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self = (IndividualRetrievalTests*) tracker_test_test_case_construct (object_type, "IndividualRetrieval");
#line 37 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_test_case_add_test ((FolksTestCase*) self, "singleton individuals", _individual_retrieval_tests_test_singleton_individuals_folks_test_case_test_method, self);
#line 33 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return self;
#line 125 "individual-retrieval.c"
}


IndividualRetrievalTests* individual_retrieval_tests_new (void) {
#line 33 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return individual_retrieval_tests_construct (TYPE_INDIVIDUAL_RETRIEVAL_TESTS);
#line 132 "individual-retrieval.c"
}


void individual_retrieval_tests_test_singleton_individuals (IndividualRetrievalTests* self) {
	GMainLoop* _tmp0_;
	GeeHashMap* _tmp1_;
	GeeHashMap* _tmp2_;
	GeeHashMap* _tmp3_;
	TrackerTestBackend* _tmp4_;
	GeeHashMap* _tmp5_;
	GeeHashMap* _tmp6_;
	TrackerTestBackend* _tmp7_;
	GeeHashMap* _tmp8_;
	TrackerTestBackend* _tmp9_;
	GMainLoop* _tmp10_;
	GeeHashMap* _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	GeeHashMap* _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
#line 40 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_return_if_fail (self != NULL);
#line 42 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp0_ = g_main_loop_new (NULL, FALSE);
#line 42 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 42 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self->priv->_main_loop = _tmp0_;
#line 43 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp1_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 43 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (self->priv->_c1);
#line 43 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self->priv->_c1 = _tmp1_;
#line 44 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp2_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 44 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (self->priv->_c2);
#line 44 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self->priv->_c2 = _tmp2_;
#line 46 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp3_ = self->priv->_c1;
#line 46 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp3_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME, "persona #1");
#line 47 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp4_ = ((TrackerTestTestCase*) self)->tracker_backend;
#line 47 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp5_ = self->priv->_c1;
#line 47 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	tracker_test_backend_add_contact (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, TRACKER_TEST_TYPE_BACKEND, TrackerTestBackend), _tmp5_);
#line 48 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp6_ = self->priv->_c2;
#line 48 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp6_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME, "persona #2");
#line 49 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp7_ = ((TrackerTestTestCase*) self)->tracker_backend;
#line 49 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp8_ = self->priv->_c2;
#line 49 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	tracker_test_backend_add_contact (G_TYPE_CHECK_INSTANCE_CAST (_tmp7_, TRACKER_TEST_TYPE_BACKEND, TrackerTestBackend), _tmp8_);
#line 50 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp9_ = ((TrackerTestTestCase*) self)->tracker_backend;
#line 50 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	tracker_test_backend_set_up (G_TYPE_CHECK_INSTANCE_CAST (_tmp9_, TRACKER_TEST_TYPE_BACKEND, TrackerTestBackend));
#line 52 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_individual_retrieval_tests_test_singleton_individuals_async (self, NULL, NULL);
#line 54 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp10_ = self->priv->_main_loop;
#line 54 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_test_utils_loop_run_with_timeout (_tmp10_, 5);
#line 56 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp11_ = self->priv->_c1;
#line 56 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp12_ = gee_abstract_map_get_size ((GeeMap*) _tmp11_);
#line 56 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp13_ = _tmp12_;
#line 56 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_vala_assert (_tmp13_ == 0, "this._c1.size == 0");
#line 57 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp14_ = self->priv->_c2;
#line 57 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp15_ = gee_abstract_map_get_size ((GeeMap*) _tmp14_);
#line 57 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp16_ = _tmp15_;
#line 57 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_vala_assert (_tmp16_ == 0, "this._c2.size == 0");
#line 220 "individual-retrieval.c"
}


static void _individual_retrieval_tests_test_singleton_individuals_async_data_free (gpointer _data) {
	IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_;
	_data_ = _data;
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (_data_->self);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_slice_free (IndividualRetrievalTestsTestSingletonIndividualsAsyncData, _data_);
#line 231 "individual-retrieval.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return self ? g_object_ref (self) : NULL;
#line 238 "individual-retrieval.c"
}


static void _individual_retrieval_tests_test_singleton_individuals_async (IndividualRetrievalTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_;
	IndividualRetrievalTests* _tmp0_;
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_ = g_slice_new0 (IndividualRetrievalTestsTestSingletonIndividualsAsyncData);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, _individual_retrieval_tests_test_singleton_individuals_async);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, _individual_retrieval_tests_test_singleton_individuals_async_data_free);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->self = _tmp0_;
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_individual_retrieval_tests_test_singleton_individuals_async_co (_data_);
#line 257 "individual-retrieval.c"
}


static void _individual_retrieval_tests_test_singleton_individuals_finish (IndividualRetrievalTests* self, GAsyncResult* _res_) {
	IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_;
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 265 "individual-retrieval.c"
}


static void _individual_retrieval_tests_test_singleton_individuals_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_ = _user_data_;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_source_object_ = source_object;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_res_ = _res_;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_individual_retrieval_tests_test_singleton_individuals_async_co (_data_);
#line 279 "individual-retrieval.c"
}


static void __individual_retrieval_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self) {
#line 65 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_individual_retrieval_tests_individuals_changed_cb (self, changes);
#line 286 "individual-retrieval.c"
}


static gboolean _individual_retrieval_tests_test_singleton_individuals_async_co (IndividualRetrievalTestsTestSingletonIndividualsAsyncData* _data_) {
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	switch (_data_->_state_) {
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		case 0:
#line 295 "individual-retrieval.c"
		goto _state_0;
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		case 1:
#line 299 "individual-retrieval.c"
		goto _state_1;
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		case 2:
#line 303 "individual-retrieval.c"
		goto _state_2;
		default:
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_assert_not_reached ();
#line 308 "individual-retrieval.c"
	}
	_state_0:
#line 62 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_tmp0_ = NULL;
#line 62 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_tmp0_ = folks_backend_store_dup ();
#line 62 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->store = _data_->_tmp0_;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_state_ = 1;
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_backend_store_prepare (_data_->store, _individual_retrieval_tests_test_singleton_individuals_async_ready, _data_);
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return FALSE;
#line 323 "individual-retrieval.c"
	_state_1:
#line 63 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_backend_store_prepare_finish (_data_->store, _data_->_res_);
#line 64 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_tmp1_ = folks_individual_aggregator_new ();
#line 64 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (_data_->self->priv->_aggregator);
#line 64 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->self->priv->_aggregator = _data_->_tmp1_;
#line 65 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_data_->_tmp2_ = _data_->self->priv->_aggregator;
#line 65 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_signal_connect_object (_data_->_tmp2_, "individuals-changed-detailed", (GCallback) __individual_retrieval_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed, _data_->self, 0);
#line 337 "individual-retrieval.c"
	{
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->_tmp3_ = _data_->self->priv->_aggregator;
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->_state_ = 2;
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		folks_individual_aggregator_prepare (_data_->_tmp3_, _individual_retrieval_tests_test_singleton_individuals_async_ready, _data_);
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		return FALSE;
#line 347 "individual-retrieval.c"
		_state_2:
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		folks_individual_aggregator_prepare_finish (_data_->_tmp3_, _data_->_res_, &_data_->_inner_error_);
#line 69 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		if (_data_->_inner_error_ != NULL) {
#line 353 "individual-retrieval.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->e = _data_->_inner_error_;
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->_inner_error_ = NULL;
#line 73 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->_tmp4_ = _data_->e;
#line 73 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_data_->_tmp5_ = _data_->_tmp4_->message;
#line 73 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_warning ("individual-retrieval.vala:73: Error when calling prepare: %s\n", _data_->_tmp5_);
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_g_error_free0 (_data_->e);
#line 372 "individual-retrieval.c"
	}
	__finally0:
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	if (_data_->_inner_error_ != NULL) {
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_g_object_unref0 (_data_->store);
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_clear_error (&_data_->_inner_error_);
#line 67 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		return FALSE;
#line 385 "individual-retrieval.c"
	}
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (_data_->store);
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	if (_data_->_state_ == 0) {
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 393 "individual-retrieval.c"
	} else {
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 397 "individual-retrieval.c"
	}
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_object_unref (_data_->_async_result);
#line 60 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return FALSE;
#line 403 "individual-retrieval.c"
}


static void _individual_retrieval_tests_individuals_changed_cb (IndividualRetrievalTests* self, GeeMultiMap* changes) {
	GeeCollection* added = NULL;
	GeeMultiMap* _tmp0_;
	GeeCollection* _tmp1_ = NULL;
	GeeSet* removed = NULL;
	GeeMultiMap* _tmp2_;
	GeeSet* _tmp3_ = NULL;
	gboolean _tmp28_ = FALSE;
	GeeHashMap* _tmp29_;
	gint _tmp30_;
	gint _tmp31_;
	gboolean _tmp35_;
	GeeSet* _tmp37_;
	gint _tmp38_;
	gint _tmp39_;
#line 77 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_return_if_fail (self != NULL);
#line 77 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_return_if_fail (changes != NULL);
#line 80 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp0_ = changes;
#line 80 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp1_ = gee_multi_map_get_values (_tmp0_);
#line 80 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	added = _tmp1_;
#line 81 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp2_ = changes;
#line 81 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp3_ = gee_multi_map_get_keys (_tmp2_);
#line 81 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	removed = _tmp3_;
#line 438 "individual-retrieval.c"
	{
		GeeIterator* _i_it = NULL;
		GeeCollection* _tmp4_;
		GeeIterator* _tmp5_ = NULL;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp4_ = added;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_i_it = _tmp5_;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		while (TRUE) {
#line 451 "individual-retrieval.c"
			GeeIterator* _tmp6_;
			gboolean _tmp7_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp8_;
			gpointer _tmp9_ = NULL;
			FolksIndividual* _tmp10_;
			gchar* full_name = NULL;
			FolksIndividual* _tmp11_;
			const gchar* _tmp12_;
			const gchar* _tmp13_;
			gchar* _tmp14_;
			const gchar* _tmp15_;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp6_ = _i_it;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			if (!_tmp7_) {
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				break;
#line 472 "individual-retrieval.c"
			}
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp8_ = _i_it;
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			i = (FolksIndividual*) _tmp9_;
#line 85 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp10_ = i;
#line 85 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_vala_assert (_tmp10_ != NULL, "i != null");
#line 87 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp11_ = i;
#line 87 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp12_ = folks_name_details_get_full_name (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, FOLKS_TYPE_NAME_DETAILS, FolksNameDetails));
#line 87 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp13_ = _tmp12_;
#line 87 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp14_ = g_strdup (_tmp13_);
#line 87 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			full_name = _tmp14_;
#line 88 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp15_ = full_name;
#line 88 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			if (_tmp15_ != NULL) {
#line 498 "individual-retrieval.c"
				GeeHashMap* _tmp16_;
				gpointer _tmp17_ = NULL;
				gchar* _tmp18_;
				const gchar* _tmp19_;
				gboolean _tmp20_;
				GeeHashMap* _tmp22_;
				gpointer _tmp23_ = NULL;
				gchar* _tmp24_;
				const gchar* _tmp25_;
				gboolean _tmp26_;
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp16_ = self->priv->_c1;
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp17_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp16_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME);
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp18_ = (gchar*) _tmp17_;
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp19_ = full_name;
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp20_ = g_strcmp0 (_tmp18_, _tmp19_) == 0;
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_g_free0 (_tmp18_);
#line 90 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				if (_tmp20_) {
#line 523 "individual-retrieval.c"
					GeeHashMap* _tmp21_;
#line 92 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
					_tmp21_ = self->priv->_c1;
#line 92 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
					gee_abstract_map_unset ((GeeAbstractMap*) _tmp21_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME, NULL);
#line 529 "individual-retrieval.c"
				}
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp22_ = self->priv->_c2;
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp23_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp22_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME);
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp24_ = (gchar*) _tmp23_;
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp25_ = full_name;
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_tmp26_ = g_strcmp0 (_tmp24_, _tmp25_) == 0;
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				_g_free0 (_tmp24_);
#line 95 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				if (_tmp26_) {
#line 545 "individual-retrieval.c"
					GeeHashMap* _tmp27_;
#line 97 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
					_tmp27_ = self->priv->_c2;
#line 97 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
					gee_abstract_map_unset ((GeeAbstractMap*) _tmp27_, TRF_ONTOLOGY_DEFS_NCO_FULLNAME, NULL);
#line 551 "individual-retrieval.c"
				}
			}
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_g_free0 (full_name);
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_g_object_unref0 (i);
#line 558 "individual-retrieval.c"
		}
#line 83 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_g_object_unref0 (_i_it);
#line 562 "individual-retrieval.c"
	}
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp29_ = self->priv->_c1;
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp30_ = gee_abstract_map_get_size ((GeeMap*) _tmp29_);
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp31_ = _tmp30_;
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	if (_tmp31_ == 0) {
#line 572 "individual-retrieval.c"
		GeeHashMap* _tmp32_;
		gint _tmp33_;
		gint _tmp34_;
#line 103 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp32_ = self->priv->_c2;
#line 103 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp33_ = gee_abstract_map_get_size ((GeeMap*) _tmp32_);
#line 103 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp34_ = _tmp33_;
#line 103 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp28_ = _tmp34_ == 0;
#line 584 "individual-retrieval.c"
	} else {
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp28_ = FALSE;
#line 588 "individual-retrieval.c"
	}
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp35_ = _tmp28_;
#line 102 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	if (_tmp35_) {
#line 594 "individual-retrieval.c"
		GMainLoop* _tmp36_;
#line 104 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp36_ = self->priv->_main_loop;
#line 104 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		g_main_loop_quit (_tmp36_);
#line 600 "individual-retrieval.c"
	}
#line 106 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp37_ = removed;
#line 106 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp38_ = gee_collection_get_size ((GeeCollection*) _tmp37_);
#line 106 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp39_ = _tmp38_;
#line 106 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_vala_assert (_tmp39_ == 1, "removed.size == 1");
#line 610 "individual-retrieval.c"
	{
		GeeIterator* _i_it = NULL;
		GeeSet* _tmp40_;
		GeeIterator* _tmp41_ = NULL;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp40_ = removed;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_tmp41_ = gee_iterable_iterator ((GeeIterable*) _tmp40_);
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_i_it = _tmp41_;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		while (TRUE) {
#line 623 "individual-retrieval.c"
			GeeIterator* _tmp42_;
			gboolean _tmp43_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp44_;
			gpointer _tmp45_ = NULL;
			FolksIndividual* _tmp46_;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp42_ = _i_it;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp43_ = gee_iterator_next (_tmp42_);
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			if (!_tmp43_) {
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
				break;
#line 638 "individual-retrieval.c"
			}
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp44_ = _i_it;
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp45_ = gee_iterator_get (_tmp44_);
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			i = (FolksIndividual*) _tmp45_;
#line 110 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_tmp46_ = i;
#line 110 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_vala_assert (_tmp46_ == NULL, "i == null");
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
			_g_object_unref0 (i);
#line 652 "individual-retrieval.c"
		}
#line 108 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
		_g_object_unref0 (_i_it);
#line 656 "individual-retrieval.c"
	}
#line 77 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (removed);
#line 77 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (added);
#line 662 "individual-retrieval.c"
}


static void individual_retrieval_tests_class_init (IndividualRetrievalTestsClass * klass) {
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	individual_retrieval_tests_parent_class = g_type_class_peek_parent (klass);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_type_class_add_private (klass, sizeof (IndividualRetrievalTestsPrivate));
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	G_OBJECT_CLASS (klass)->finalize = individual_retrieval_tests_finalize;
#line 673 "individual-retrieval.c"
}


static void individual_retrieval_tests_instance_init (IndividualRetrievalTests * self) {
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self->priv = INDIVIDUAL_RETRIEVAL_TESTS_GET_PRIVATE (self);
#line 680 "individual-retrieval.c"
}


static void individual_retrieval_tests_finalize (GObject* obj) {
	IndividualRetrievalTests * self;
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_INDIVIDUAL_RETRIEVAL_TESTS, IndividualRetrievalTests);
#line 28 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 29 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (self->priv->_aggregator);
#line 30 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (self->priv->_c1);
#line 31 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (self->priv->_c2);
#line 26 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	G_OBJECT_CLASS (individual_retrieval_tests_parent_class)->finalize (obj);
#line 698 "individual-retrieval.c"
}


GType individual_retrieval_tests_get_type (void) {
	static volatile gsize individual_retrieval_tests_type_id__volatile = 0;
	if (g_once_init_enter (&individual_retrieval_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (IndividualRetrievalTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) individual_retrieval_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (IndividualRetrievalTests), 0, (GInstanceInitFunc) individual_retrieval_tests_instance_init, NULL };
		GType individual_retrieval_tests_type_id;
		individual_retrieval_tests_type_id = g_type_register_static (TRACKER_TEST_TYPE_TEST_CASE, "IndividualRetrievalTests", &g_define_type_info, 0);
		g_once_init_leave (&individual_retrieval_tests_type_id__volatile, individual_retrieval_tests_type_id);
	}
	return individual_retrieval_tests_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	IndividualRetrievalTests* tests = NULL;
	IndividualRetrievalTests* _tmp0_;
#line 117 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_test_init (&args_length1, &args, NULL);
#line 119 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_tmp0_ = individual_retrieval_tests_new ();
#line 119 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	tests = _tmp0_;
#line 120 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_test_case_register ((FolksTestCase*) tests);
#line 121 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_test_run ();
#line 122 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	folks_test_case_final_tear_down ((FolksTestCase*) tests);
#line 124 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	result = 0;
#line 124 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	_g_object_unref0 (tests);
#line 124 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return result;
#line 736 "individual-retrieval.c"
}


int main (int argc, char ** argv) {
#line 115 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	g_type_init ();
#line 115 "/home/treitter/collabora/folks/tests/tracker/individual-retrieval.vala"
	return _vala_main (argv, argc);
#line 745 "individual-retrieval.c"
}



