/* remove-persona.c generated by valac 0.20.1.30-1b1d, the Vala compiler
 * generated from remove-persona.vala, do not modify */

/*
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Raul Gutierrez Segales <raul.gutierrez.segales@collabora.co.uk>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <eds-test.h>
#include <folks/folks.h>
#include <stdlib.h>
#include <string.h>
#include <folks-test.h>
#include <gio/gio.h>
#include <gee.h>
#include <folks/folks-eds.h>


#define TYPE_REMOVE_PERSONA_TESTS (remove_persona_tests_get_type ())
#define REMOVE_PERSONA_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REMOVE_PERSONA_TESTS, RemovePersonaTests))
#define REMOVE_PERSONA_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REMOVE_PERSONA_TESTS, RemovePersonaTestsClass))
#define IS_REMOVE_PERSONA_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REMOVE_PERSONA_TESTS))
#define IS_REMOVE_PERSONA_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REMOVE_PERSONA_TESTS))
#define REMOVE_PERSONA_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REMOVE_PERSONA_TESTS, RemovePersonaTestsClass))

typedef struct _RemovePersonaTests RemovePersonaTests;
typedef struct _RemovePersonaTestsClass RemovePersonaTestsClass;
typedef struct _RemovePersonaTestsPrivate RemovePersonaTestsPrivate;
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _RemovePersonaTestsTestRemovePersonaAsyncData RemovePersonaTestsTestRemovePersonaAsyncData;
#define __vala_GValue_free0(var) ((var == NULL) ? NULL : (var = (_vala_GValue_free (var), NULL)))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
typedef struct _RemovePersonaTestsAddPersonaData RemovePersonaTestsAddPersonaData;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _RemovePersonaTests {
	EdsTestTestCase parent_instance;
	RemovePersonaTestsPrivate * priv;
};

struct _RemovePersonaTestsClass {
	EdsTestTestCaseClass parent_class;
};

struct _RemovePersonaTestsPrivate {
	GMainLoop* _main_loop;
	FolksIndividualAggregator* _aggregator;
	gchar* _persona_fullname;
	gboolean _persona_removed;
	gboolean _individual_removed;
	gchar* _individual_id;
	FolksPersonaStore* _pstore;
	gchar* _persona_id;
	FolksIndividual* _individual;
	gboolean _added_persona;
};

struct _RemovePersonaTestsTestRemovePersonaAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	RemovePersonaTests* self;
	FolksBackendStore* store;
	FolksBackendStore* _tmp0_;
	FolksIndividualAggregator* _tmp1_;
	FolksIndividualAggregator* _tmp2_;
	FolksIndividualAggregator* _tmp3_;
	GeeIterator* _backend_it;
	GeeMap* _tmp4_;
	GeeMap* _tmp5_;
	GeeCollection* _tmp6_;
	GeeCollection* _tmp7_;
	GeeCollection* _tmp8_;
	GeeIterator* _tmp9_;
	GeeIterator* _tmp10_;
	GeeIterator* _tmp11_;
	gboolean _tmp12_;
	FolksBackend* backend;
	GeeIterator* _tmp13_;
	gpointer _tmp14_;
	FolksBackend* _tmp15_;
	GeeMap* _tmp16_;
	GeeMap* _tmp17_;
	EdsTestBackend* _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	gpointer _tmp21_;
	FolksPersonaStore* _tmp22_;
	FolksPersonaStore* _tmp23_;
	FolksPersonaStore* _tmp24_;
	GError* e;
	GError* _tmp25_;
	const gchar* _tmp26_;
	GError * _inner_error_;
};

struct _RemovePersonaTestsAddPersonaData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	RemovePersonaTests* self;
	GHashTable* details;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	GValue* v1;
	GValue _tmp3_;
	GValue _tmp4_;
	GValue* _tmp5_;
	GValue* _tmp6_;
	GValue* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	GValue* _tmp11_;
	FolksIndividualAggregator* _tmp12_;
	FolksPersonaStore* _tmp13_;
	FolksPersona* _tmp14_;
	FolksPersona* _tmp15_;
	GError* e;
	GError* _tmp16_;
	const gchar* _tmp17_;
	GError * _inner_error_;
};


static gpointer remove_persona_tests_parent_class = NULL;

GType remove_persona_tests_get_type (void) G_GNUC_CONST;
#define REMOVE_PERSONA_TESTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_REMOVE_PERSONA_TESTS, RemovePersonaTestsPrivate))
enum  {
	REMOVE_PERSONA_TESTS_DUMMY_PROPERTY
};
RemovePersonaTests* remove_persona_tests_new (void);
RemovePersonaTests* remove_persona_tests_construct (GType object_type);
void remove_persona_tests_test_remove_persona (RemovePersonaTests* self);
static void _remove_persona_tests_test_remove_persona_folks_test_case_test_method (gpointer self);
static void _remove_persona_tests_test_remove_persona_async (RemovePersonaTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void _remove_persona_tests_test_remove_persona_finish (RemovePersonaTests* self, GAsyncResult* _res_);
static void _remove_persona_tests_test_remove_persona_async_data_free (gpointer _data);
static gboolean _remove_persona_tests_test_remove_persona_async_co (RemovePersonaTestsTestRemovePersonaAsyncData* _data_);
static void _remove_persona_tests_test_remove_persona_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _remove_persona_tests_individuals_changed_cb (RemovePersonaTests* self, GeeMultiMap* changes);
static void __remove_persona_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self);
static void _remove_persona_tests_notify_pstore_cb (RemovePersonaTests* self, GObject* _pstore, GParamSpec* ps);
static void __remove_persona_tests_notify_pstore_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void _remove_persona_tests_try_to_add (RemovePersonaTests* self);
static void _remove_persona_tests_add_persona (RemovePersonaTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void _remove_persona_tests_add_persona_finish (RemovePersonaTests* self, GAsyncResult* _res_);
static void _remove_persona_tests_add_persona_data_free (gpointer _data);
static gboolean _remove_persona_tests_add_persona_co (RemovePersonaTestsAddPersonaData* _data_);
static void _g_free0_ (gpointer var);
static void _vala_GValue_free (GValue* self);
static void __vala_GValue_free0_ (gpointer var);
static GValue* _g_value_dup (GValue* self);
static void _remove_persona_tests_add_persona_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _remove_persona_tests_personas_cb (RemovePersonaTests* self);
static void __remove_persona_tests_personas_cb_folks_persona_store_personas_changed (FolksPersonaStore* _sender, GeeSet* added, GeeSet* removed, const gchar* message, FolksPersona* actor, FolksGroupDetailsChangeReason reason, gpointer self);
static void remove_persona_tests_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


static void _remove_persona_tests_test_remove_persona_folks_test_case_test_method (gpointer self) {
#line 41 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	remove_persona_tests_test_remove_persona (self);
#line 189 "remove-persona.c"
}


RemovePersonaTests* remove_persona_tests_construct (GType object_type) {
	RemovePersonaTests * self = NULL;
#line 39 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self = (RemovePersonaTests*) eds_test_test_case_construct (object_type, "RemovePersonaTests");
#line 41 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_test_case_add_test ((FolksTestCase*) self, "test removing personas from e-d-s ", _remove_persona_tests_test_remove_persona_folks_test_case_test_method, self);
#line 37 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return self;
#line 201 "remove-persona.c"
}


RemovePersonaTests* remove_persona_tests_new (void) {
#line 37 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return remove_persona_tests_construct (TYPE_REMOVE_PERSONA_TESTS);
#line 208 "remove-persona.c"
}


void remove_persona_tests_test_remove_persona (RemovePersonaTests* self) {
	GMainLoop* _tmp0_;
	gchar* _tmp1_;
	GMainLoop* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
#line 45 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (self != NULL);
#line 47 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = g_main_loop_new (NULL, FALSE);
#line 47 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 47 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv->_main_loop = _tmp0_;
#line 48 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp1_ = g_strdup ("persona #1");
#line 48 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_free0 (self->priv->_persona_fullname);
#line 48 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv->_persona_fullname = _tmp1_;
#line 50 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv->_persona_removed = FALSE;
#line 51 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv->_individual_removed = FALSE;
#line 53 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_test_remove_persona_async (self, NULL, NULL);
#line 55 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp2_ = self->priv->_main_loop;
#line 55 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_test_utils_loop_run_with_timeout (_tmp2_, 5);
#line 57 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp3_ = self->priv->_persona_removed;
#line 57 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_vala_assert (_tmp3_ == TRUE, "this._persona_removed == true");
#line 58 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp4_ = self->priv->_individual_removed;
#line 58 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_vala_assert (_tmp4_ == TRUE, "this._individual_removed == true");
#line 250 "remove-persona.c"
}


static void _remove_persona_tests_test_remove_persona_async_data_free (gpointer _data) {
	RemovePersonaTestsTestRemovePersonaAsyncData* _data_;
	_data_ = _data;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (_data_->self);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_slice_free (RemovePersonaTestsTestRemovePersonaAsyncData, _data_);
#line 261 "remove-persona.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return self ? g_object_ref (self) : NULL;
#line 268 "remove-persona.c"
}


static void _remove_persona_tests_test_remove_persona_async (RemovePersonaTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	RemovePersonaTestsTestRemovePersonaAsyncData* _data_;
	RemovePersonaTests* _tmp0_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = g_slice_new0 (RemovePersonaTestsTestRemovePersonaAsyncData);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, _remove_persona_tests_test_remove_persona_async);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, _remove_persona_tests_test_remove_persona_async_data_free);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->self = _tmp0_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_test_remove_persona_async_co (_data_);
#line 287 "remove-persona.c"
}


static void _remove_persona_tests_test_remove_persona_finish (RemovePersonaTests* self, GAsyncResult* _res_) {
	RemovePersonaTestsTestRemovePersonaAsyncData* _data_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 295 "remove-persona.c"
}


static void _remove_persona_tests_test_remove_persona_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	RemovePersonaTestsTestRemovePersonaAsyncData* _data_;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = _user_data_;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_source_object_ = source_object;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_res_ = _res_;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_test_remove_persona_async_co (_data_);
#line 309 "remove-persona.c"
}


static void __remove_persona_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self) {
#line 66 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_individuals_changed_cb (self, changes);
#line 316 "remove-persona.c"
}


static void __remove_persona_tests_notify_pstore_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 83 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_notify_pstore_cb (self, _sender, pspec);
#line 323 "remove-persona.c"
}


static gboolean _remove_persona_tests_test_remove_persona_async_co (RemovePersonaTestsTestRemovePersonaAsyncData* _data_) {
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	switch (_data_->_state_) {
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		case 0:
#line 332 "remove-persona.c"
		goto _state_0;
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		case 1:
#line 336 "remove-persona.c"
		goto _state_1;
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		case 2:
#line 340 "remove-persona.c"
		goto _state_2;
		default:
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_assert_not_reached ();
#line 345 "remove-persona.c"
	}
	_state_0:
#line 63 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp0_ = NULL;
#line 63 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp0_ = folks_backend_store_dup ();
#line 63 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->store = _data_->_tmp0_;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_state_ = 1;
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_backend_store_prepare (_data_->store, _remove_persona_tests_test_remove_persona_async_ready, _data_);
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return FALSE;
#line 360 "remove-persona.c"
	_state_1:
#line 64 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_backend_store_prepare_finish (_data_->store, _data_->_res_);
#line 65 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp1_ = folks_individual_aggregator_new ();
#line 65 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (_data_->self->priv->_aggregator);
#line 65 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->self->priv->_aggregator = _data_->_tmp1_;
#line 66 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp2_ = _data_->self->priv->_aggregator;
#line 66 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_signal_connect_object (_data_->_tmp2_, "individuals-changed-detailed", (GCallback) __remove_persona_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed, _data_->self, 0);
#line 374 "remove-persona.c"
	{
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp3_ = _data_->self->priv->_aggregator;
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_state_ = 2;
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		folks_individual_aggregator_prepare (_data_->_tmp3_, _remove_persona_tests_test_remove_persona_async_ready, _data_);
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		return FALSE;
#line 384 "remove-persona.c"
		_state_2:
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		folks_individual_aggregator_prepare_finish (_data_->_tmp3_, _data_->_res_, &_data_->_inner_error_);
#line 70 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		if (_data_->_inner_error_ != NULL) {
#line 390 "remove-persona.c"
			goto __catch0_g_error;
		}
#line 72 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_object_unref0 (_data_->self->priv->_pstore);
#line 72 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->self->priv->_pstore = NULL;
#line 397 "remove-persona.c"
		{
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp4_ = folks_backend_store_get_enabled_backends (_data_->store);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp5_ = _data_->_tmp4_;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp6_ = gee_map_get_values (_data_->_tmp5_);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp7_ = _data_->_tmp6_;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp8_ = _data_->_tmp7_;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp9_ = NULL;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp9_ = gee_iterable_iterator ((GeeIterable*) _data_->_tmp8_);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_tmp10_ = _data_->_tmp9_;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_g_object_unref0 (_data_->_tmp8_);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_data_->_backend_it = _data_->_tmp10_;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			while (TRUE) {
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp11_ = _data_->_backend_it;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp12_ = FALSE;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp12_ = gee_iterator_next (_data_->_tmp11_);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				if (!_data_->_tmp12_) {
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					break;
#line 431 "remove-persona.c"
				}
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp13_ = _data_->_backend_it;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp14_ = NULL;
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp14_ = gee_iterator_get (_data_->_tmp13_);
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->backend = (FolksBackend*) _data_->_tmp14_;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp15_ = _data_->backend;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp16_ = folks_backend_get_persona_stores (_data_->_tmp15_);
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp17_ = _data_->_tmp16_;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp18_ = ((EdsTestTestCase*) _data_->self)->eds_backend;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp19_ = eds_test_backend_get_address_book_uid (_data_->_tmp18_);
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp20_ = _data_->_tmp19_;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp21_ = NULL;
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp21_ = gee_map_get (_data_->_tmp17_, _data_->_tmp20_);
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_object_unref0 (_data_->self->priv->_pstore);
#line 75 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->self->priv->_pstore = (FolksPersonaStore*) G_TYPE_CHECK_INSTANCE_CAST ((FolksPersonaStore*) _data_->_tmp21_, EDSF_TYPE_PERSONA_STORE, EdsfPersonaStore);
#line 78 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_data_->_tmp22_ = _data_->self->priv->_pstore;
#line 78 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				if (_data_->_tmp22_ != NULL) {
#line 79 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_g_object_unref0 (_data_->backend);
#line 79 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					break;
#line 469 "remove-persona.c"
				}
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_object_unref0 (_data_->backend);
#line 473 "remove-persona.c"
			}
#line 73 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_g_object_unref0 (_data_->_backend_it);
#line 477 "remove-persona.c"
		}
#line 81 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp23_ = _data_->self->priv->_pstore;
#line 81 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_vala_assert (_data_->_tmp23_ != NULL, "this._pstore != null");
#line 83 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp24_ = _data_->self->priv->_pstore;
#line 83 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_signal_connect_object ((GObject*) _data_->_tmp24_, "notify::is-prepared", (GCallback) __remove_persona_tests_notify_pstore_cb_g_object_notify, _data_->self, 0);
#line 84 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_remove_persona_tests_try_to_add (_data_->self);
#line 489 "remove-persona.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->e = _data_->_inner_error_;
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_inner_error_ = NULL;
#line 88 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp25_ = _data_->e;
#line 88 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp26_ = _data_->_tmp25_->message;
#line 88 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_warning ("remove-persona.vala:88: Error when calling prepare: %s\n", _data_->_tmp26_);
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_error_free0 (_data_->e);
#line 506 "remove-persona.c"
	}
	__finally0:
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_data_->_inner_error_ != NULL) {
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_object_unref0 (_data_->store);
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_clear_error (&_data_->_inner_error_);
#line 68 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		return FALSE;
#line 519 "remove-persona.c"
	}
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (_data_->store);
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_data_->_state_ == 0) {
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 527 "remove-persona.c"
	} else {
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 531 "remove-persona.c"
	}
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_object_unref (_data_->_async_result);
#line 61 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return FALSE;
#line 537 "remove-persona.c"
}


static void _remove_persona_tests_notify_pstore_cb (RemovePersonaTests* self, GObject* _pstore, GParamSpec* ps) {
#line 92 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (self != NULL);
#line 92 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (_pstore != NULL);
#line 92 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (ps != NULL);
#line 94 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_try_to_add (self);
#line 550 "remove-persona.c"
}


static void _remove_persona_tests_try_to_add (RemovePersonaTests* self) {
	gboolean _tmp0_ = FALSE;
	FolksPersonaStore* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp5_;
#line 97 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (self != NULL);
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp1_ = self->priv->_pstore;
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp2_ = folks_persona_store_get_is_prepared (_tmp1_);
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp3_ = _tmp2_;
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_tmp3_) {
#line 570 "remove-persona.c"
		gboolean _tmp4_;
#line 100 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp4_ = self->priv->_added_persona;
#line 100 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp0_ = _tmp4_ == FALSE;
#line 576 "remove-persona.c"
	} else {
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp0_ = FALSE;
#line 580 "remove-persona.c"
	}
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp5_ = _tmp0_;
#line 99 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_tmp5_) {
#line 102 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		self->priv->_added_persona = TRUE;
#line 103 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_remove_persona_tests_add_persona (self, NULL, NULL);
#line 590 "remove-persona.c"
	}
}


static void _remove_persona_tests_add_persona_data_free (gpointer _data) {
	RemovePersonaTestsAddPersonaData* _data_;
	_data_ = _data;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (_data_->self);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_slice_free (RemovePersonaTestsAddPersonaData, _data_);
#line 602 "remove-persona.c"
}


static void _remove_persona_tests_add_persona (RemovePersonaTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	RemovePersonaTestsAddPersonaData* _data_;
	RemovePersonaTests* _tmp0_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = g_slice_new0 (RemovePersonaTestsAddPersonaData);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, _remove_persona_tests_add_persona);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, _remove_persona_tests_add_persona_data_free);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->self = _tmp0_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_add_persona_co (_data_);
#line 621 "remove-persona.c"
}


static void _remove_persona_tests_add_persona_finish (RemovePersonaTests* self, GAsyncResult* _res_) {
	RemovePersonaTestsAddPersonaData* _data_;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 629 "remove-persona.c"
}


static void _g_free0_ (gpointer var) {
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	var = (g_free (var), NULL);
#line 636 "remove-persona.c"
}


static void _vala_GValue_free (GValue* self) {
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_value_unset (self);
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_free (self);
#line 645 "remove-persona.c"
}


static void __vala_GValue_free0_ (gpointer var) {
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	(var == NULL) ? NULL : (var = (_vala_GValue_free (var), NULL));
#line 652 "remove-persona.c"
}


static GValue* _g_value_dup (GValue* self) {
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return g_boxed_copy (G_TYPE_VALUE, self);
#line 659 "remove-persona.c"
}


static gpointer __g_value_dup0 (gpointer self) {
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return self ? _g_value_dup (self) : NULL;
#line 666 "remove-persona.c"
}


static void _remove_persona_tests_add_persona_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	RemovePersonaTestsAddPersonaData* _data_;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_ = _user_data_;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_source_object_ = source_object;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_res_ = _res_;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_add_persona_co (_data_);
#line 680 "remove-persona.c"
}


static gboolean _remove_persona_tests_add_persona_co (RemovePersonaTestsAddPersonaData* _data_) {
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	switch (_data_->_state_) {
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		case 0:
#line 689 "remove-persona.c"
		goto _state_0;
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		case 1:
#line 693 "remove-persona.c"
		goto _state_1;
		default:
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_assert_not_reached ();
#line 698 "remove-persona.c"
	}
	_state_0:
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp0_ = g_str_hash;
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp1_ = g_str_equal;
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp2_ = g_hash_table_new_full (_data_->_tmp0_, _data_->_tmp1_, _g_free0_, __vala_GValue_free0_);
#line 109 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->details = _data_->_tmp2_;
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	memset (&_data_->_tmp3_, 0, sizeof (GValue));
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_value_init (&_data_->_tmp3_, G_TYPE_STRING);
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp4_ = _data_->_tmp3_;
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp5_ = __g_value_dup0 (&_data_->_tmp4_);
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp6_ = _data_->_tmp5_;
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	G_IS_VALUE (&_data_->_tmp4_) ? (g_value_unset (&_data_->_tmp4_), NULL) : NULL;
#line 111 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->v1 = _data_->_tmp6_;
#line 112 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp7_ = _data_->v1;
#line 112 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp8_ = _data_->self->priv->_persona_fullname;
#line 112 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_value_set_string (_data_->_tmp7_, _data_->_tmp8_);
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp9_ = NULL;
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp9_ = folks_persona_store_detail_key (FOLKS_PERSONA_DETAIL_FULL_NAME);
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp10_ = g_strdup (_data_->_tmp9_);
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->_tmp11_ = _data_->v1;
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_data_->v1 = NULL;
#line 113 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_hash_table_insert (_data_->details, _data_->_tmp10_, _data_->_tmp11_);
#line 741 "remove-persona.c"
	{
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp12_ = _data_->self->priv->_aggregator;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp13_ = _data_->self->priv->_pstore;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_state_ = 1;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		folks_individual_aggregator_add_persona_from_details (_data_->_tmp12_, NULL, _data_->_tmp13_, _data_->details, _remove_persona_tests_add_persona_ready, _data_);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		return FALSE;
#line 753 "remove-persona.c"
		_state_1:
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp14_ = NULL;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp14_ = folks_individual_aggregator_add_persona_from_details_finish (_data_->_tmp12_, _data_->_res_, &_data_->_inner_error_);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp15_ = _data_->_tmp14_;
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_object_unref0 (_data_->_tmp15_);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		if (_data_->_inner_error_ != NULL) {
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (_data_->_inner_error_->domain == FOLKS_INDIVIDUAL_AGGREGATOR_ERROR) {
#line 767 "remove-persona.c"
				goto __catch1_folks_individual_aggregator_error;
			}
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			__vala_GValue_free0 (_data_->v1);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_g_hash_table_unref0 (_data_->details);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			g_clear_error (&_data_->_inner_error_);
#line 118 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			return FALSE;
#line 780 "remove-persona.c"
		}
	}
	goto __finally1;
	__catch1_folks_individual_aggregator_error:
	{
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->e = _data_->_inner_error_;
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_inner_error_ = NULL;
#line 123 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp16_ = _data_->e;
#line 123 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_data_->_tmp17_ = _data_->_tmp16_->message;
#line 123 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_warning ("remove-persona.vala:123: [RemovePersonaError] add_persona_from_details" \
": %s\n", _data_->_tmp17_);
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_error_free0 (_data_->e);
#line 798 "remove-persona.c"
	}
	__finally1:
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_data_->_inner_error_ != NULL) {
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		__vala_GValue_free0 (_data_->v1);
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_hash_table_unref0 (_data_->details);
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_clear_error (&_data_->_inner_error_);
#line 116 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		return FALSE;
#line 813 "remove-persona.c"
	}
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	__vala_GValue_free0 (_data_->v1);
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_hash_table_unref0 (_data_->details);
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_data_->_state_ == 0) {
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 823 "remove-persona.c"
	} else {
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 827 "remove-persona.c"
	}
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_object_unref (_data_->_async_result);
#line 107 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return FALSE;
#line 833 "remove-persona.c"
}


static void __remove_persona_tests_personas_cb_folks_persona_store_personas_changed (FolksPersonaStore* _sender, GeeSet* added, GeeSet* removed, const gchar* message, FolksPersona* actor, FolksGroupDetailsChangeReason reason, gpointer self) {
#line 155 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_remove_persona_tests_personas_cb (self);
#line 840 "remove-persona.c"
}


static void _remove_persona_tests_individuals_changed_cb (RemovePersonaTests* self, GeeMultiMap* changes) {
	GeeCollection* added = NULL;
	GeeMultiMap* _tmp0_;
	GeeCollection* _tmp1_ = NULL;
	GeeSet* removed = NULL;
	GeeMultiMap* _tmp2_;
	GeeSet* _tmp3_ = NULL;
#line 128 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (self != NULL);
#line 128 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (changes != NULL);
#line 131 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = changes;
#line 131 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp1_ = gee_multi_map_get_values (_tmp0_);
#line 131 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	added = _tmp1_;
#line 132 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp2_ = changes;
#line 132 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp3_ = gee_multi_map_get_keys (_tmp2_);
#line 132 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	removed = _tmp3_;
#line 867 "remove-persona.c"
	{
		GeeIterator* _i_it = NULL;
		GeeCollection* _tmp4_;
		GeeIterator* _tmp5_ = NULL;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp4_ = added;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_i_it = _tmp5_;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		while (TRUE) {
#line 880 "remove-persona.c"
			GeeIterator* _tmp6_;
			gboolean _tmp7_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp8_;
			gpointer _tmp9_ = NULL;
			FolksIndividual* _tmp10_;
			FolksIndividual* _tmp11_;
			const gchar* _tmp12_;
			const gchar* _tmp13_;
			const gchar* _tmp14_;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp6_ = _i_it;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (!_tmp7_) {
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				break;
#line 899 "remove-persona.c"
			}
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp8_ = _i_it;
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			i = (FolksIndividual*) _tmp9_;
#line 136 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp10_ = i;
#line 136 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (_tmp10_ == NULL) {
#line 138 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_object_unref0 (i);
#line 138 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				continue;
#line 915 "remove-persona.c"
			}
#line 141 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp11_ = i;
#line 141 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp12_ = folks_name_details_get_full_name ((FolksNameDetails*) _tmp11_);
#line 141 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp13_ = _tmp12_;
#line 141 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp14_ = self->priv->_persona_fullname;
#line 141 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (g_strcmp0 (_tmp13_, _tmp14_) == 0) {
#line 927 "remove-persona.c"
				FolksIndividual* _tmp15_;
				const gchar* _tmp16_;
				const gchar* _tmp17_;
				gchar* _tmp18_;
				FolksIndividual* _tmp31_;
				FolksIndividual* _tmp32_;
				FolksPersonaStore* _tmp33_;
				GeeMap* _tmp34_;
				GeeMap* _tmp35_;
				const gchar* _tmp36_;
				gboolean _tmp37_ = FALSE;
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp15_ = i;
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp16_ = folks_individual_get_id (_tmp15_);
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp17_ = _tmp16_;
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp18_ = g_strdup (_tmp17_);
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_free0 (self->priv->_individual_id);
#line 143 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				self->priv->_individual_id = _tmp18_;
#line 951 "remove-persona.c"
				{
					GeeIterator* _p_it = NULL;
					FolksIndividual* _tmp19_;
					GeeSet* _tmp20_;
					GeeSet* _tmp21_;
					GeeIterator* _tmp22_ = NULL;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp19_ = i;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp20_ = folks_individual_get_personas (_tmp19_);
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp21_ = _tmp20_;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp22_ = gee_iterable_iterator ((GeeIterable*) _tmp21_);
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_p_it = _tmp22_;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					while (TRUE) {
#line 970 "remove-persona.c"
						GeeIterator* _tmp23_;
						gboolean _tmp24_ = FALSE;
						FolksPersona* p = NULL;
						GeeIterator* _tmp25_;
						gpointer _tmp26_ = NULL;
						FolksPersona* _tmp27_;
						const gchar* _tmp28_;
						const gchar* _tmp29_;
						gchar* _tmp30_;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp23_ = _p_it;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp24_ = gee_iterator_next (_tmp23_);
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						if (!_tmp24_) {
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
							break;
#line 988 "remove-persona.c"
						}
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp25_ = _p_it;
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp26_ = gee_iterator_get (_tmp25_);
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						p = (FolksPersona*) _tmp26_;
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp27_ = p;
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp28_ = folks_persona_get_iid (_tmp27_);
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp29_ = _tmp28_;
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_tmp30_ = g_strdup (_tmp29_);
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_g_free0 (self->priv->_persona_id);
#line 148 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						self->priv->_persona_id = _tmp30_;
#line 149 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						_g_object_unref0 (p);
#line 149 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
						break;
#line 1012 "remove-persona.c"
					}
#line 146 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_g_object_unref0 (_p_it);
#line 1016 "remove-persona.c"
				}
#line 152 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp31_ = i;
#line 152 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp32_ = _g_object_ref0 (_tmp31_);
#line 152 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_object_unref0 (self->priv->_individual);
#line 152 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				self->priv->_individual = _tmp32_;
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp33_ = self->priv->_pstore;
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp34_ = folks_persona_store_get_personas (_tmp33_);
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp35_ = _tmp34_;
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp36_ = self->priv->_persona_id;
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_tmp37_ = gee_map_has_key (_tmp35_, _tmp36_);
#line 153 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				if (_tmp37_ == TRUE) {
#line 1038 "remove-persona.c"
					FolksPersonaStore* _tmp38_;
					FolksIndividualAggregator* _tmp39_;
					FolksIndividual* _tmp40_;
#line 155 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp38_ = self->priv->_pstore;
#line 155 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					g_signal_connect_object (_tmp38_, "personas-changed", (GCallback) __remove_persona_tests_personas_cb_folks_persona_store_personas_changed, self, 0);
#line 156 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp39_ = self->priv->_aggregator;
#line 156 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					_tmp40_ = self->priv->_individual;
#line 156 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
					folks_individual_aggregator_remove_individual (_tmp39_, _tmp40_, NULL, NULL);
#line 1052 "remove-persona.c"
				}
			}
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_g_object_unref0 (i);
#line 1057 "remove-persona.c"
		}
#line 134 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_object_unref0 (_i_it);
#line 1061 "remove-persona.c"
	}
	{
		GeeIterator* _i_it = NULL;
		GeeSet* _tmp41_;
		GeeIterator* _tmp42_ = NULL;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp41_ = removed;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp42_ = gee_iterable_iterator ((GeeIterable*) _tmp41_);
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_i_it = _tmp42_;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		while (TRUE) {
#line 1075 "remove-persona.c"
			GeeIterator* _tmp43_;
			gboolean _tmp44_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp45_;
			gpointer _tmp46_ = NULL;
			FolksIndividual* _tmp47_;
			FolksIndividual* _tmp48_;
			const gchar* _tmp49_;
			const gchar* _tmp50_;
			const gchar* _tmp51_;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp43_ = _i_it;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp44_ = gee_iterator_next (_tmp43_);
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (!_tmp44_) {
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				break;
#line 1094 "remove-persona.c"
			}
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp45_ = _i_it;
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp46_ = gee_iterator_get (_tmp45_);
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			i = (FolksIndividual*) _tmp46_;
#line 163 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp47_ = i;
#line 163 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (_tmp47_ == NULL) {
#line 165 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				_g_object_unref0 (i);
#line 165 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				continue;
#line 1110 "remove-persona.c"
			}
#line 168 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp48_ = i;
#line 168 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp49_ = folks_individual_get_id (_tmp48_);
#line 168 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp50_ = _tmp49_;
#line 168 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_tmp51_ = self->priv->_individual_id;
#line 168 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			if (g_strcmp0 (_tmp50_, _tmp51_) == 0) {
#line 170 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
				self->priv->_individual_removed = TRUE;
#line 1124 "remove-persona.c"
			}
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
			_g_object_unref0 (i);
#line 1128 "remove-persona.c"
		}
#line 161 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_g_object_unref0 (_i_it);
#line 1132 "remove-persona.c"
	}
#line 128 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (removed);
#line 128 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (added);
#line 1138 "remove-persona.c"
}


static void _remove_persona_tests_personas_cb (RemovePersonaTests* self) {
	FolksPersonaStore* _tmp0_;
	GeeMap* _tmp1_;
	GeeMap* _tmp2_;
	const gchar* _tmp3_;
	gboolean _tmp4_ = FALSE;
#line 175 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_return_if_fail (self != NULL);
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = self->priv->_pstore;
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp1_ = folks_persona_store_get_personas (_tmp0_);
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp2_ = _tmp1_;
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp3_ = self->priv->_persona_id;
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp4_ = gee_map_has_key (_tmp2_, _tmp3_);
#line 177 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	if (_tmp4_ == FALSE) {
#line 1162 "remove-persona.c"
		GMainLoop* _tmp5_;
#line 179 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		self->priv->_persona_removed = TRUE;
#line 180 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		_tmp5_ = self->priv->_main_loop;
#line 180 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
		g_main_loop_quit (_tmp5_);
#line 1170 "remove-persona.c"
	}
}


static void remove_persona_tests_class_init (RemovePersonaTestsClass * klass) {
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	remove_persona_tests_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_type_class_add_private (klass, sizeof (RemovePersonaTestsPrivate));
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	G_OBJECT_CLASS (klass)->finalize = remove_persona_tests_finalize;
#line 1182 "remove-persona.c"
}


static void remove_persona_tests_instance_init (RemovePersonaTests * self) {
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv = REMOVE_PERSONA_TESTS_GET_PRIVATE (self);
#line 35 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self->priv->_added_persona = FALSE;
#line 1191 "remove-persona.c"
}


static void remove_persona_tests_finalize (GObject* obj) {
	RemovePersonaTests * self;
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_REMOVE_PERSONA_TESTS, RemovePersonaTests);
#line 26 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 27 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (self->priv->_aggregator);
#line 28 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_free0 (self->priv->_persona_fullname);
#line 31 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_free0 (self->priv->_individual_id);
#line 32 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (self->priv->_pstore);
#line 33 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_free0 (self->priv->_persona_id);
#line 34 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (self->priv->_individual);
#line 24 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	G_OBJECT_CLASS (remove_persona_tests_parent_class)->finalize (obj);
#line 1215 "remove-persona.c"
}


GType remove_persona_tests_get_type (void) {
	static volatile gsize remove_persona_tests_type_id__volatile = 0;
	if (g_once_init_enter (&remove_persona_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RemovePersonaTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) remove_persona_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RemovePersonaTests), 0, (GInstanceInitFunc) remove_persona_tests_instance_init, NULL };
		GType remove_persona_tests_type_id;
		remove_persona_tests_type_id = g_type_register_static (EDS_TEST_TYPE_TEST_CASE, "RemovePersonaTests", &g_define_type_info, 0);
		g_once_init_leave (&remove_persona_tests_type_id__volatile, remove_persona_tests_type_id);
	}
	return remove_persona_tests_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	RemovePersonaTests* tests = NULL;
	RemovePersonaTests* _tmp0_;
#line 187 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_test_init (&args_length1, &args, NULL);
#line 189 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_tmp0_ = remove_persona_tests_new ();
#line 189 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	tests = _tmp0_;
#line 190 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_test_case_register ((FolksTestCase*) tests);
#line 191 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_test_run ();
#line 192 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	folks_test_case_final_tear_down ((FolksTestCase*) tests);
#line 194 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	result = 0;
#line 194 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	_g_object_unref0 (tests);
#line 194 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return result;
#line 1253 "remove-persona.c"
}


int main (int argc, char ** argv) {
#line 185 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	g_type_init ();
#line 185 "/home/treitter/collabora/folks/tests/eds/remove-persona.vala"
	return _vala_main (argv, argc);
#line 1262 "remove-persona.c"
}



