/* set-structured-name.c generated by valac 0.20.1.30-1b1d, the Vala compiler
 * generated from set-structured-name.vala, do not modify */

/*
 * Copyright (C) 2011 Collabora Ltd.
 *
 * This library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Authors: Raul Gutierrez Segales <raul.gutierrez.segales@collabora.co.uk>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <eds-test.h>
#include <folks/folks.h>
#include <folks-test.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define TYPE_SET_STRUCTURED_NAME_TESTS (set_structured_name_tests_get_type ())
#define SET_STRUCTURED_NAME_TESTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SET_STRUCTURED_NAME_TESTS, SetStructuredNameTests))
#define SET_STRUCTURED_NAME_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SET_STRUCTURED_NAME_TESTS, SetStructuredNameTestsClass))
#define IS_SET_STRUCTURED_NAME_TESTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SET_STRUCTURED_NAME_TESTS))
#define IS_SET_STRUCTURED_NAME_TESTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SET_STRUCTURED_NAME_TESTS))
#define SET_STRUCTURED_NAME_TESTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SET_STRUCTURED_NAME_TESTS, SetStructuredNameTestsClass))

typedef struct _SetStructuredNameTests SetStructuredNameTests;
typedef struct _SetStructuredNameTestsClass SetStructuredNameTestsClass;
typedef struct _SetStructuredNameTestsPrivate SetStructuredNameTestsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_main_loop_unref0(var) ((var == NULL) ? NULL : (var = (g_main_loop_unref (var), NULL)))
#define __vala_GValue_free0(var) ((var == NULL) ? NULL : (var = (_vala_GValue_free (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _SetStructuredNameTestsTestSetStructuredNameAsyncData SetStructuredNameTestsTestSetStructuredNameAsyncData;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _SetStructuredNameTests {
	EdsTestTestCase parent_instance;
	SetStructuredNameTestsPrivate * priv;
};

struct _SetStructuredNameTestsClass {
	EdsTestTestCaseClass parent_class;
};

struct _SetStructuredNameTestsPrivate {
	FolksIndividualAggregator* _aggregator;
	GMainLoop* _main_loop;
	gboolean _found_before_update;
	gboolean _found_after_update;
	FolksStructuredName* _sname;
};

struct _SetStructuredNameTestsTestSetStructuredNameAsyncData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	SetStructuredNameTests* self;
	EdsTestBackend* _tmp0_;
	FolksBackendStore* store;
	FolksBackendStore* _tmp1_;
	FolksIndividualAggregator* _tmp2_;
	FolksIndividualAggregator* _tmp3_;
	FolksIndividualAggregator* _tmp4_;
	GError* e;
	GError* _tmp5_;
	const gchar* _tmp6_;
	GError * _inner_error_;
};


static gpointer set_structured_name_tests_parent_class = NULL;

GType set_structured_name_tests_get_type (void) G_GNUC_CONST;
#define SET_STRUCTURED_NAME_TESTS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SET_STRUCTURED_NAME_TESTS, SetStructuredNameTestsPrivate))
enum  {
	SET_STRUCTURED_NAME_TESTS_DUMMY_PROPERTY
};
SetStructuredNameTests* set_structured_name_tests_new (void);
SetStructuredNameTests* set_structured_name_tests_construct (GType object_type);
static void set_structured_name_tests_test_set_structured_name (SetStructuredNameTests* self);
static void _set_structured_name_tests_test_set_structured_name_folks_test_case_test_method (gpointer self);
static GValue* _g_value_dup (GValue* self);
static void _vala_GValue_free (GValue* self);
static void _set_structured_name_tests_test_set_structured_name_async (SetStructuredNameTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void _set_structured_name_tests_test_set_structured_name_finish (SetStructuredNameTests* self, GAsyncResult* _res_);
static void _set_structured_name_tests_test_set_structured_name_async_data_free (gpointer _data);
static gboolean _set_structured_name_tests_test_set_structured_name_async_co (SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_);
static void _set_structured_name_tests_test_set_structured_name_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void _set_structured_name_tests_individuals_changed_cb (SetStructuredNameTests* self, GeeMultiMap* changes);
static void __set_structured_name_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self);
static void _set_structured_name_tests_notify_structured_name_cb (SetStructuredNameTests* self, GObject* individual_obj, GParamSpec* ps);
static void __set_structured_name_tests_notify_structured_name_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void set_structured_name_tests_finalize (GObject* obj);
gint _vala_main (gchar** args, int args_length1);


static void _set_structured_name_tests_test_set_structured_name_folks_test_case_test_method (gpointer self) {
#line 37 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	set_structured_name_tests_test_set_structured_name (self);
#line 118 "set-structured-name.c"
}


SetStructuredNameTests* set_structured_name_tests_construct (GType object_type) {
	SetStructuredNameTests * self = NULL;
#line 35 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self = (SetStructuredNameTests*) eds_test_test_case_construct (object_type, "SetStructuredName");
#line 37 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_test_case_add_test ((FolksTestCase*) self, "setting structured name on e-d-s persona", _set_structured_name_tests_test_set_structured_name_folks_test_case_test_method, self);
#line 33 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return self;
#line 130 "set-structured-name.c"
}


SetStructuredNameTests* set_structured_name_tests_new (void) {
#line 33 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return set_structured_name_tests_construct (TYPE_SET_STRUCTURED_NAME_TESTS);
#line 137 "set-structured-name.c"
}


static GValue* _g_value_dup (GValue* self) {
#line 43 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return g_boxed_copy (G_TYPE_VALUE, self);
#line 144 "set-structured-name.c"
}


static void _vala_GValue_free (GValue* self) {
#line 43 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_value_unset (self);
#line 43 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_free (self);
#line 153 "set-structured-name.c"
}


static gpointer __g_value_dup0 (gpointer self) {
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return self ? _g_value_dup (self) : NULL;
#line 160 "set-structured-name.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 56 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return self ? g_object_ref (self) : NULL;
#line 167 "set-structured-name.c"
}


static void set_structured_name_tests_test_set_structured_name (SetStructuredNameTests* self) {
	GeeHashMap* c1 = NULL;
	GeeHashMap* _tmp0_;
	GMainLoop* _tmp1_;
	FolksStructuredName* _tmp2_;
	GValue* v = NULL;
	EdsTestBackend* _tmp3_;
	GValue _tmp4_ = {0};
	GValue _tmp5_;
	GValue* _tmp6_;
	GValue* _tmp7_;
	GValue* _tmp8_;
	GValue* _tmp9_;
	EdsTestBackend* _tmp10_;
	GeeHashMap* _tmp11_;
	GMainLoop* _tmp12_;
	gboolean _tmp13_;
	gboolean _tmp14_;
#line 41 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (self != NULL);
#line 43 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, G_TYPE_VALUE, (GBoxedCopyFunc) _g_value_dup, _vala_GValue_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 43 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	c1 = _tmp0_;
#line 44 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp1_ = g_main_loop_new (NULL, FALSE);
#line 44 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 44 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self->priv->_main_loop = _tmp1_;
#line 45 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp2_ = folks_structured_name_new_simple ("Innocenti", "Bernie");
#line 45 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (self->priv->_sname);
#line 45 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self->priv->_sname = _tmp2_;
#line 48 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self->priv->_found_before_update = FALSE;
#line 49 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self->priv->_found_after_update = FALSE;
#line 51 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp3_ = ((EdsTestTestCase*) self)->eds_backend;
#line 51 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	eds_test_backend_reset (_tmp3_);
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_value_init (&_tmp4_, G_TYPE_STRING);
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp5_ = _tmp4_;
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp6_ = __g_value_dup0 (&_tmp5_);
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	__vala_GValue_free0 (v);
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	v = _tmp6_;
#line 53 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	G_IS_VALUE (&_tmp5_) ? (g_value_unset (&_tmp5_), NULL) : NULL;
#line 54 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp7_ = v;
#line 54 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_value_set_string (_tmp7_, "bernie h. innocenti");
#line 55 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp8_ = v;
#line 55 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	v = NULL;
#line 55 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp9_ = _tmp8_;
#line 55 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	gee_abstract_map_set ((GeeAbstractMap*) c1, "full_name", _tmp9_);
#line 55 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	__vala_GValue_free0 (_tmp9_);
#line 56 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp10_ = ((EdsTestTestCase*) self)->eds_backend;
#line 56 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp11_ = _g_object_ref0 (c1);
#line 56 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	eds_test_backend_add_contact (_tmp10_, _tmp11_);
#line 58 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_set_structured_name_tests_test_set_structured_name_async (self, NULL, NULL);
#line 60 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp12_ = self->priv->_main_loop;
#line 60 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_test_utils_loop_run_with_timeout (_tmp12_, 5);
#line 62 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp13_ = self->priv->_found_before_update;
#line 62 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_vala_assert (_tmp13_, "this._found_before_update");
#line 63 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp14_ = self->priv->_found_after_update;
#line 63 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_vala_assert (_tmp14_, "this._found_after_update");
#line 41 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	__vala_GValue_free0 (v);
#line 41 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (c1);
#line 265 "set-structured-name.c"
}


static void _set_structured_name_tests_test_set_structured_name_async_data_free (gpointer _data) {
	SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_;
	_data_ = _data;
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (_data_->self);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_slice_free (SetStructuredNameTestsTestSetStructuredNameAsyncData, _data_);
#line 276 "set-structured-name.c"
}


static void _set_structured_name_tests_test_set_structured_name_async (SetStructuredNameTests* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_;
	SetStructuredNameTests* _tmp0_;
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_ = g_slice_new0 (SetStructuredNameTestsTestSetStructuredNameAsyncData);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, _set_structured_name_tests_test_set_structured_name_async);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, _set_structured_name_tests_test_set_structured_name_async_data_free);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->self = _tmp0_;
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_set_structured_name_tests_test_set_structured_name_async_co (_data_);
#line 295 "set-structured-name.c"
}


static void _set_structured_name_tests_test_set_structured_name_finish (SetStructuredNameTests* self, GAsyncResult* _res_) {
	SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_;
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
#line 303 "set-structured-name.c"
}


static void _set_structured_name_tests_test_set_structured_name_async_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_ = _user_data_;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_source_object_ = source_object;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_res_ = _res_;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_set_structured_name_tests_test_set_structured_name_async_co (_data_);
#line 317 "set-structured-name.c"
}


static void __set_structured_name_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed (FolksIndividualAggregator* _sender, GeeMultiMap* changes, gpointer self) {
#line 73 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_set_structured_name_tests_individuals_changed_cb (self, changes);
#line 324 "set-structured-name.c"
}


static gboolean _set_structured_name_tests_test_set_structured_name_async_co (SetStructuredNameTestsTestSetStructuredNameAsyncData* _data_) {
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	switch (_data_->_state_) {
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		case 0:
#line 333 "set-structured-name.c"
		goto _state_0;
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		case 1:
#line 337 "set-structured-name.c"
		goto _state_1;
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		case 2:
#line 341 "set-structured-name.c"
		goto _state_2;
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		case 3:
#line 345 "set-structured-name.c"
		goto _state_3;
		default:
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_assert_not_reached ();
#line 350 "set-structured-name.c"
	}
	_state_0:
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_tmp0_ = ((EdsTestTestCase*) _data_->self)->eds_backend;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_state_ = 1;
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	eds_test_backend_commit_contacts_to_addressbook (_data_->_tmp0_, _set_structured_name_tests_test_set_structured_name_async_ready, _data_);
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return FALSE;
#line 361 "set-structured-name.c"
	_state_1:
#line 68 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	eds_test_backend_commit_contacts_to_addressbook_finish (_data_->_tmp0_, _data_->_res_);
#line 70 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_tmp1_ = NULL;
#line 70 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_tmp1_ = folks_backend_store_dup ();
#line 70 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->store = _data_->_tmp1_;
#line 71 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_state_ = 2;
#line 71 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_backend_store_prepare (_data_->store, _set_structured_name_tests_test_set_structured_name_async_ready, _data_);
#line 71 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return FALSE;
#line 377 "set-structured-name.c"
	_state_2:
#line 71 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_backend_store_prepare_finish (_data_->store, _data_->_res_);
#line 72 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_tmp2_ = folks_individual_aggregator_new ();
#line 72 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (_data_->self->priv->_aggregator);
#line 72 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->self->priv->_aggregator = _data_->_tmp2_;
#line 73 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_data_->_tmp3_ = _data_->self->priv->_aggregator;
#line 73 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_signal_connect_object (_data_->_tmp3_, "individuals-changed-detailed", (GCallback) __set_structured_name_tests_individuals_changed_cb_folks_individual_aggregator_individuals_changed_detailed, _data_->self, 0);
#line 391 "set-structured-name.c"
	{
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->_tmp4_ = _data_->self->priv->_aggregator;
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->_state_ = 3;
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		folks_individual_aggregator_prepare (_data_->_tmp4_, _set_structured_name_tests_test_set_structured_name_async_ready, _data_);
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		return FALSE;
#line 401 "set-structured-name.c"
		_state_3:
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		folks_individual_aggregator_prepare_finish (_data_->_tmp4_, _data_->_res_, &_data_->_inner_error_);
#line 77 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		if (_data_->_inner_error_ != NULL) {
#line 407 "set-structured-name.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->e = _data_->_inner_error_;
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->_inner_error_ = NULL;
#line 81 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->_tmp5_ = _data_->e;
#line 81 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_data_->_tmp6_ = _data_->_tmp5_->message;
#line 81 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_warning ("set-structured-name.vala:81: Error when calling prepare: %s\n", _data_->_tmp6_);
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_g_error_free0 (_data_->e);
#line 426 "set-structured-name.c"
	}
	__finally0:
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	if (_data_->_inner_error_ != NULL) {
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_g_object_unref0 (_data_->store);
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_clear_error (&_data_->_inner_error_);
#line 75 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		return FALSE;
#line 439 "set-structured-name.c"
	}
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (_data_->store);
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	if (_data_->_state_ == 0) {
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_simple_async_result_complete_in_idle (_data_->_async_result);
#line 447 "set-structured-name.c"
	} else {
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_simple_async_result_complete (_data_->_async_result);
#line 451 "set-structured-name.c"
	}
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_object_unref (_data_->_async_result);
#line 66 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return FALSE;
#line 457 "set-structured-name.c"
}


static void __set_structured_name_tests_notify_structured_name_cb_g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
#line 99 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_set_structured_name_tests_notify_structured_name_cb (self, _sender, pspec);
#line 464 "set-structured-name.c"
}


static void _set_structured_name_tests_individuals_changed_cb (SetStructuredNameTests* self, GeeMultiMap* changes) {
	GeeCollection* added = NULL;
	GeeMultiMap* _tmp0_;
	GeeCollection* _tmp1_ = NULL;
	GeeSet* removed = NULL;
	GeeMultiMap* _tmp2_;
	GeeSet* _tmp3_ = NULL;
	GeeSet* _tmp27_;
	gint _tmp28_;
	gint _tmp29_;
#line 85 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (self != NULL);
#line 85 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (changes != NULL);
#line 88 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp0_ = changes;
#line 88 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp1_ = gee_multi_map_get_values (_tmp0_);
#line 88 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	added = _tmp1_;
#line 89 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp2_ = changes;
#line 89 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp3_ = gee_multi_map_get_keys (_tmp2_);
#line 89 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	removed = _tmp3_;
#line 494 "set-structured-name.c"
	{
		GeeIterator* _i_it = NULL;
		GeeCollection* _tmp4_;
		GeeIterator* _tmp5_ = NULL;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_tmp4_ = added;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_tmp5_ = gee_iterable_iterator ((GeeIterable*) _tmp4_);
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_i_it = _tmp5_;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		while (TRUE) {
#line 507 "set-structured-name.c"
			GeeIterator* _tmp6_;
			gboolean _tmp7_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp8_;
			gpointer _tmp9_ = NULL;
			FolksIndividual* _tmp10_;
			FolksNameDetails* name = NULL;
			FolksIndividual* _tmp11_;
			FolksNameDetails* _tmp12_;
			FolksNameDetails* _tmp13_;
			const gchar* _tmp14_;
			const gchar* _tmp15_;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp6_ = _i_it;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp7_ = gee_iterator_next (_tmp6_);
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			if (!_tmp7_) {
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
				break;
#line 528 "set-structured-name.c"
			}
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp8_ = _i_it;
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp9_ = gee_iterator_get (_tmp8_);
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			i = (FolksIndividual*) _tmp9_;
#line 93 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp10_ = i;
#line 93 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_vala_assert (_tmp10_ != NULL, "i != null");
#line 95 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp11_ = i;
#line 95 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp12_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp11_, FOLKS_TYPE_NAME_DETAILS, FolksNameDetails));
#line 95 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			name = _tmp12_;
#line 97 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp13_ = name;
#line 97 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp14_ = folks_name_details_get_full_name (_tmp13_);
#line 97 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp15_ = _tmp14_;
#line 97 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			if (g_strcmp0 (_tmp15_, "bernie h. innocenti") == 0) {
#line 554 "set-structured-name.c"
				FolksIndividual* _tmp16_;
#line 99 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
				_tmp16_ = i;
#line 99 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
				g_signal_connect_object ((GObject*) _tmp16_, "notify::structured-name", (GCallback) __set_structured_name_tests_notify_structured_name_cb_g_object_notify, self, 0);
#line 101 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
				self->priv->_found_before_update = TRUE;
#line 562 "set-structured-name.c"
				{
					GeeIterator* _p_it = NULL;
					FolksIndividual* _tmp17_;
					GeeSet* _tmp18_;
					GeeSet* _tmp19_;
					GeeIterator* _tmp20_ = NULL;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_tmp17_ = i;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_tmp18_ = folks_individual_get_personas (_tmp17_);
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_tmp19_ = _tmp18_;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_tmp20_ = gee_iterable_iterator ((GeeIterable*) _tmp19_);
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_p_it = _tmp20_;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					while (TRUE) {
#line 581 "set-structured-name.c"
						GeeIterator* _tmp21_;
						gboolean _tmp22_ = FALSE;
						FolksPersona* p = NULL;
						GeeIterator* _tmp23_;
						gpointer _tmp24_ = NULL;
						FolksPersona* _tmp25_;
						FolksStructuredName* _tmp26_;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp21_ = _p_it;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp22_ = gee_iterator_next (_tmp21_);
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						if (!_tmp22_) {
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
							break;
#line 597 "set-structured-name.c"
						}
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp23_ = _p_it;
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp24_ = gee_iterator_get (_tmp23_);
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						p = (FolksPersona*) _tmp24_;
#line 105 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp25_ = p;
#line 105 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_tmp26_ = self->priv->_sname;
#line 105 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						folks_name_details_set_structured_name (G_TYPE_CHECK_INSTANCE_CAST (_tmp25_, FOLKS_TYPE_NAME_DETAILS, FolksNameDetails), _tmp26_);
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
						_g_object_unref0 (p);
#line 613 "set-structured-name.c"
					}
#line 103 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
					_g_object_unref0 (_p_it);
#line 617 "set-structured-name.c"
				}
			}
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_g_object_unref0 (name);
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_g_object_unref0 (i);
#line 624 "set-structured-name.c"
		}
#line 91 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_g_object_unref0 (_i_it);
#line 628 "set-structured-name.c"
	}
#line 110 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp27_ = removed;
#line 110 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp28_ = gee_collection_get_size ((GeeCollection*) _tmp27_);
#line 110 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp29_ = _tmp28_;
#line 110 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_vala_assert (_tmp29_ == 1, "removed.size == 1");
#line 638 "set-structured-name.c"
	{
		GeeIterator* _i_it = NULL;
		GeeSet* _tmp30_;
		GeeIterator* _tmp31_ = NULL;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_tmp30_ = removed;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_tmp31_ = gee_iterable_iterator ((GeeIterable*) _tmp30_);
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_i_it = _tmp31_;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		while (TRUE) {
#line 651 "set-structured-name.c"
			GeeIterator* _tmp32_;
			gboolean _tmp33_ = FALSE;
			FolksIndividual* i = NULL;
			GeeIterator* _tmp34_;
			gpointer _tmp35_ = NULL;
			FolksIndividual* _tmp36_;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp32_ = _i_it;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp33_ = gee_iterator_next (_tmp32_);
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			if (!_tmp33_) {
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
				break;
#line 666 "set-structured-name.c"
			}
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp34_ = _i_it;
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp35_ = gee_iterator_get (_tmp34_);
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			i = (FolksIndividual*) _tmp35_;
#line 114 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_tmp36_ = i;
#line 114 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_vala_assert (_tmp36_ == NULL, "i == null");
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
			_g_object_unref0 (i);
#line 680 "set-structured-name.c"
		}
#line 112 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_g_object_unref0 (_i_it);
#line 684 "set-structured-name.c"
	}
#line 85 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (removed);
#line 85 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (added);
#line 690 "set-structured-name.c"
}


static void _set_structured_name_tests_notify_structured_name_cb (SetStructuredNameTests* self, GObject* individual_obj, GParamSpec* ps) {
	FolksIndividual* i = NULL;
	GObject* _tmp0_;
	FolksIndividual* _tmp1_;
	FolksIndividual* _tmp2_;
	FolksStructuredName* _tmp3_;
	FolksStructuredName* _tmp4_;
	FolksStructuredName* _tmp5_;
	gboolean _tmp6_ = FALSE;
#line 118 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (self != NULL);
#line 118 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (individual_obj != NULL);
#line 118 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_return_if_fail (ps != NULL);
#line 120 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp0_ = individual_obj;
#line 120 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, FOLKS_TYPE_INDIVIDUAL, FolksIndividual));
#line 120 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	i = _tmp1_;
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp2_ = i;
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp3_ = folks_name_details_get_structured_name ((FolksNameDetails*) _tmp2_);
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp4_ = _tmp3_;
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp5_ = self->priv->_sname;
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp6_ = folks_structured_name_equal (_tmp4_, _tmp5_);
#line 121 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	if (_tmp6_) {
#line 727 "set-structured-name.c"
		GMainLoop* _tmp7_;
#line 123 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		self->priv->_found_after_update = TRUE;
#line 124 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		_tmp7_ = self->priv->_main_loop;
#line 124 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
		g_main_loop_quit (_tmp7_);
#line 735 "set-structured-name.c"
	}
#line 118 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (i);
#line 739 "set-structured-name.c"
}


static void set_structured_name_tests_class_init (SetStructuredNameTestsClass * klass) {
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	set_structured_name_tests_parent_class = g_type_class_peek_parent (klass);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_type_class_add_private (klass, sizeof (SetStructuredNameTestsPrivate));
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	G_OBJECT_CLASS (klass)->finalize = set_structured_name_tests_finalize;
#line 750 "set-structured-name.c"
}


static void set_structured_name_tests_instance_init (SetStructuredNameTests * self) {
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self->priv = SET_STRUCTURED_NAME_TESTS_GET_PRIVATE (self);
#line 757 "set-structured-name.c"
}


static void set_structured_name_tests_finalize (GObject* obj) {
	SetStructuredNameTests * self;
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SET_STRUCTURED_NAME_TESTS, SetStructuredNameTests);
#line 27 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (self->priv->_aggregator);
#line 28 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_main_loop_unref0 (self->priv->_main_loop);
#line 31 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (self->priv->_sname);
#line 25 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	G_OBJECT_CLASS (set_structured_name_tests_parent_class)->finalize (obj);
#line 773 "set-structured-name.c"
}


GType set_structured_name_tests_get_type (void) {
	static volatile gsize set_structured_name_tests_type_id__volatile = 0;
	if (g_once_init_enter (&set_structured_name_tests_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SetStructuredNameTestsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) set_structured_name_tests_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SetStructuredNameTests), 0, (GInstanceInitFunc) set_structured_name_tests_instance_init, NULL };
		GType set_structured_name_tests_type_id;
		set_structured_name_tests_type_id = g_type_register_static (EDS_TEST_TYPE_TEST_CASE, "SetStructuredNameTests", &g_define_type_info, 0);
		g_once_init_leave (&set_structured_name_tests_type_id__volatile, set_structured_name_tests_type_id);
	}
	return set_structured_name_tests_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	SetStructuredNameTests* tests = NULL;
	SetStructuredNameTests* _tmp0_;
#line 131 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_test_init (&args_length1, &args, NULL);
#line 133 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_tmp0_ = set_structured_name_tests_new ();
#line 133 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	tests = _tmp0_;
#line 134 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_test_case_register ((FolksTestCase*) tests);
#line 135 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_test_run ();
#line 136 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	folks_test_case_final_tear_down ((FolksTestCase*) tests);
#line 138 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	result = 0;
#line 138 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	_g_object_unref0 (tests);
#line 138 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return result;
#line 811 "set-structured-name.c"
}


int main (int argc, char ** argv) {
#line 129 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	g_type_init ();
#line 129 "/home/treitter/collabora/folks/tests/eds/set-structured-name.vala"
	return _vala_main (argv, argc);
#line 820 "set-structured-name.c"
}



